# Generated by Django 2.2.12 on 2022-02-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='bearing_counter',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pump',
            name='oil_counter',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pump',
            name='rotor_counter',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pump',
            name='sealant_counter',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pump',
            name='shaft_counter',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pump',
            name='wheel_counter',
            field=models.IntegerField(null=True),
        ),
    ]
