# Generated by Django 3.2.10 on 2021-12-28 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modellist',
            options={'ordering': ['name'], 'verbose_name': 'model_list', 'verbose_name_plural': 'model_lists'},
        ),
    ]
