# Generated by Django 4.0.8 on 2022-11-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_property',
            name='PROPERTY_BINARY',
            field=models.BinaryField(db_index=True, max_length=200, null=True),
        ),
    ]
