# Generated by Django 4.1.8 on 2023-04-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_property',
            name='LAYER_NAME',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item_property',
            name='END_DATETIME',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='item_property',
            name='ITEM_ID',
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='item_property',
            name='ITEM_TYPE',
            field=models.CharField(db_index=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='item_property',
            name='LAST_UPDT_DATE',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='item_property',
            name='PROPERTY_INFO',
            field=models.CharField(db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='item_property',
            name='PROPERTY_TYPE',
            field=models.CharField(db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='item_property',
            name='ROW_ID',
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='item_property',
            name='START_DATETIME',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='item_property',
            name='VERSION',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
