# Generated by Django 4.0.8 on 2022-11-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_property', '0002_item_property_property_binary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_property',
            name='PROPERTY_BINARY',
        ),
    ]
