# Generated by Django 4.0.8 on 2022-11-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_property', '0004_item_property_property_binary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_property',
            name='PROPERTY_BINARY',
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
    ]
