from django.db import models 
import uuid 
from django.utils import timezone 
class code_list(models.Model): 
	LIST_TYPE=models.CharField(max_length=100,primary_key=False,null=False,db_index=True,)
	CULTURE=models.CharField(max_length=10,default="Culture",primary_key=False,null=False,db_index=True,)
	CODE=models.CharField(max_length=100,primary_key=False,null=False,db_index=True,)
	CODE_TEXT=models.CharField(max_length=100,primary_key=False,null=True,db_index=True,)
	PARENT=models.CharField(max_length=100,primary_key=False,null=True,db_index=True,)
	LEGACY_CODE=models.CharField(max_length=50,primary_key=False,null=True,)
	VAL1=models.DecimalField(max_digits=28,decimal_places=12,primary_key=False,null=True,)
	VAL2=models.DecimalField(max_digits=28,decimal_places=12,primary_key=False,null=True,)
	VAL3=models.DecimalField(max_digits=28,decimal_places=12,primary_key=False,null=True,)
	VAL4=models.DecimalField(max_digits=28,decimal_places=12,primary_key=False,null=True,)
	VAL5=models.DecimalField(max_digits=28,decimal_places=12,primary_key=False,null=True,)
	VAL6=models.DecimalField(max_digits=28,decimal_places=12,primary_key=False,null=True,)
	VAL7=models.DecimalField(max_digits=28,decimal_places=12,primary_key=False,null=True,)
	VAL8=models.DecimalField(max_digits=28,decimal_places=12,primary_key=False,null=True,)
	VAL9=models.DecimalField(max_digits=28,decimal_places=12,primary_key=False,null=True,)
	VAL10=models.DecimalField(max_digits=28,decimal_places=12,primary_key=False,null=True,)
	DATE1=models.DateField(primary_key=False,null=True,)
	DATE2=models.DateField(primary_key=False,null=True,)
	DATE3=models.DateField(primary_key=False,null=True,)
	DATE4=models.DateField(primary_key=False,null=True,)
	DATE5=models.DateField(primary_key=False,null=True,)
	CHAR1=models.CharField(max_length=1000,primary_key=False,null=True,)
	CHAR2=models.CharField(max_length=1000,primary_key=False,null=True,)
	CHAR3=models.CharField(max_length=1000,primary_key=False,null=True,)
	CHAR4=models.CharField(max_length=1000,primary_key=False,null=True,)
	CHAR5=models.CharField(max_length=1000,primary_key=False,null=True,)
	LAYER_NAME=models.CharField(max_length=50,primary_key=False,null=False,)
	DESCRIPTION_ID=models.CharField(max_length=100,primary_key=False,null=True,)
	HIDDEN=models.CharField(max_length=5,primary_key=False,null=True,)
	LAST_UPDT_USER=models.CharField(max_length=100,primary_key=False,null=True,)
	LAST_UPDT_DATE=models.DateField(default=timezone.now,primary_key=False,null=True,)
	VERSION=models.CharField(max_length=32,default=uuid.uuid4,primary_key=False,null=False,)
	DB_ID=models.CharField(max_length=32,primary_key=False,null=True,)
	ROW_ID=models.CharField(max_length=32,default=uuid.uuid4,primary_key=False,null=False,)
	STATUS=models.CharField(max_length=10,primary_key=False,null=True,)
	REV_GRP_ID=models.CharField(max_length=32,primary_key=False,null=True,)
