# Generated by Django 4.1.8 on 2023-04-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bi_widget',
            fields=[
                ('WIDGET_ID', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('WIDGET_TYPE', models.CharField(db_index=True, max_length=50)),
                ('START_DATETIME', models.DateField(db_index=True)),
                ('END_DATETIME', models.DateField(db_index=True)),
                ('LAST_UPDT_USER', models.CharField(max_length=100, null=True)),
                ('LAST_UPDT_DATE', models.DateField(null=True)),
                ('VERSION', models.CharField(max_length=32)),
                ('DB_ID', models.CharField(max_length=32, null=True)),
                ('ROW_ID', models.CharField(db_index=True, max_length=32)),
                ('STATUS', models.CharField(max_length=10, null=True)),
                ('LAYER_NAME', models.CharField(max_length=50, null=True)),
                ('REV_GRP_ID', models.CharField(max_length=32, null=True)),
                ('UPDATE_SOURCE', models.CharField(default='x', max_length=1, null=True)),
                ('CREATE_SOURCE', models.CharField(default='x', max_length=1, null=True)),
            ],
        ),
    ]
