# Generated by Django 3.2.8 on 2021-11-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0002_rename_parent_company_company_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_domain',
            name='create_source',
            field=models.CharField(blank=True, db_column='create_source', default='DJANGO', editable=False, max_length=100, null=True, verbose_name='Create Source'),
        ),
    ]
