# Generated by Django 3.2.10 on 2021-12-28 11:38

import apps.db_models.models._base_domain
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base_domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True, db_column='start_datetime', default=django.utils.timezone.now, verbose_name='Datetime')),
                ('end_datetime', models.DateTimeField(db_column='end_datetime', default=apps.db_models.models._base_domain.end_datetime, verbose_name='End Datetime')),
                ('name', models.CharField(db_column='name', max_length=100, unique=True, verbose_name='Name')),
                ('short_name', models.CharField(db_column='short_name', max_length=100, unique=True, verbose_name='Short Name')),
                ('active', models.BooleanField(db_column='active', default=True, verbose_name='Active')),
                ('operated', models.BooleanField(db_column='operated', default=True, verbose_name='Operated')),
                ('last_updt_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update Date')),
                ('row_id', models.UUIDField(db_column='row_id', default=uuid.uuid4, editable=False, null=True, verbose_name='Row ID')),
                ('create_source', models.CharField(blank=True, db_column='create_source', default='DJANGO', max_length=100, null=True, verbose_name='Create Source')),
                ('update_source', models.CharField(blank=True, db_column='update_source', max_length=100, null=True, verbose_name='Update Source')),
                ('version', models.CharField(blank=True, db_column='version', max_length=100, null=True, verbose_name='Version')),
                ('accounting_id', models.CharField(blank=True, db_column='accounting_id', max_length=100, null=True, verbose_name='Accounting ID')),
                ('serial_id', models.CharField(blank=True, db_column='serial_id', max_length=100, null=True, verbose_name='Serial ID')),
                ('registry_id', models.CharField(blank=True, db_column='registry_id', max_length=100, null=True, verbose_name='Registry ID')),
                ('last_updt_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last Update User')),
            ],
            options={
                'verbose_name': 'base_domain',
                'verbose_name_plural': 'base_domains',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Base_equip',
            fields=[
                ('base_domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db_models.base_domain')),
                ('latitude', models.CharField(blank=True, db_column='latitude', max_length=100, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, db_column='longitude', max_length=100, null=True, verbose_name='Longitude')),
                ('code', models.CharField(blank=True, db_column='code', max_length=100, null=True, verbose_name='Code')),
                ('direct_entry', models.BooleanField(db_column='direct_entry', default=False, verbose_name='Manual')),
                ('scada', models.BooleanField(db_column='SCADA', default=True, verbose_name='SCADA')),
            ],
            options={
                'verbose_name': 'base_equip',
                'verbose_name_plural': 'base_equips',
            },
            bases=('db_models.base_domain',),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('base_domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db_models.base_domain')),
                ('country', models.CharField(blank=True, db_column='country', max_length=100, null=True, verbose_name='Country')),
                ('region', models.CharField(blank=True, db_column='region', max_length=100, null=True, verbose_name='Region')),
                ('subregion', models.CharField(blank=True, db_column='subregion', max_length=100, null=True, verbose_name='Sub-Region')),
                ('city', models.CharField(blank=True, db_column='city', max_length=100, null=True, verbose_name='City')),
                ('contact_name', models.CharField(blank=True, db_column='contact_name', max_length=100, null=True, verbose_name='Contact Name')),
                ('address', models.CharField(blank=True, db_column='address', max_length=100, null=True, verbose_name='Address')),
                ('email', models.EmailField(blank=True, db_column='email', max_length=100, null=True, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=100, null=True, verbose_name='Phone')),
                ('operator', models.BooleanField(blank=True, db_column='operator', default=True, verbose_name='Operator')),
                ('owner', models.BooleanField(blank=True, db_column='owner', default=True, verbose_name='Owner')),
                ('purchaser', models.BooleanField(blank=True, db_column='purchaser', default=True, verbose_name='Purchaser')),
                ('transporter', models.BooleanField(blank=True, db_column='transporter', default=True, verbose_name='Transporter')),
                ('service', models.BooleanField(blank=True, db_column='service', default=False, verbose_name='Service Provider')),
                ('company_ref', models.ManyToManyField(blank=True, to='db_models.Company', verbose_name='Parent Company')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
            bases=('db_models.base_domain',),
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('base_equip_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db_models.base_equip')),
                ('metric_system', models.CharField(blank=True, choices=[('IMPERIAL', 'Imperial'), ('METRIC', 'Metric')], db_column='metric_system', max_length=100, null=True, verbose_name='Metric System')),
                ('density', models.DecimalField(blank=True, db_column='density', decimal_places=100, max_digits=1000, null=True)),
                ('temperature', models.DecimalField(blank=True, db_column='temperature', decimal_places=100, max_digits=1000, null=True)),
            ],
            options={
                'verbose_name': 'pump',
                'verbose_name_plural': 'pumps',
            },
            bases=('db_models.base_equip',),
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('base_domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db_models.base_domain')),
                ('latitude', models.CharField(blank=True, db_column='latitude', max_length=100, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, db_column='longitude', max_length=100, null=True, verbose_name='Longitude')),
                ('product', models.CharField(blank=True, db_column='product', max_length=100, null=True, verbose_name='Product')),
                ('country', models.CharField(blank=True, db_column='country', max_length=100, null=True, verbose_name='Country')),
                ('region', models.CharField(blank=True, db_column='region', max_length=100, null=True, verbose_name='Region')),
                ('subregion', models.CharField(blank=True, db_column='subregion', max_length=100, null=True, verbose_name='Sub-Region')),
                ('city', models.CharField(blank=True, db_column='city', max_length=100, null=True, verbose_name='City')),
                ('company_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_models.company', verbose_name='Company Ref.')),
            ],
            options={
                'verbose_name': 'field',
                'verbose_name_plural': 'fields',
            },
            bases=('db_models.base_domain',),
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('base_domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db_models.base_domain')),
                ('latitude', models.CharField(blank=True, db_column='latitude', max_length=100, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, db_column='longitude', max_length=100, null=True, verbose_name='Longitude')),
                ('type', models.CharField(blank=True, db_column='type', max_length=100, null=True, verbose_name='Type')),
                ('product', models.CharField(blank=True, db_column='product', max_length=100, null=True, verbose_name='Product')),
                ('day_start', models.DateTimeField(blank=True, null=True, verbose_name='Prod. Start')),
                ('code', models.CharField(blank=True, db_column='code', max_length=100, null=True, verbose_name='Code')),
                ('direct_entry', models.BooleanField(db_column='direct_entry', default=False, verbose_name='Manual')),
                ('scada', models.BooleanField(db_column='SCADA', default=True, verbose_name='SCADA')),
                ('battery_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_models.battery', verbose_name='Battery Ref.')),
                ('company_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_models.company', verbose_name='Company Ref.')),
                ('field_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_models.field', verbose_name='Field Ref.')),
            ],
            options={
                'verbose_name': 'battery',
                'verbose_name_plural': 'batteries',
            },
            bases=('db_models.base_domain',),
        ),
        migrations.AddField(
            model_name='base_equip',
            name='battery_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_models.battery', verbose_name='Battery Ref.'),
        ),
    ]
