# Generated by Django 3.2.10 on 2021-12-28 21:20

import apps.db_models.models._base_domain
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Start Datetime')),
                ('end_datetime', models.DateTimeField(default=apps.db_models.models._base_domain.end_datetime, verbose_name='End Datetime')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Short Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('operated', models.BooleanField(default=True, verbose_name='Operated')),
                ('last_updt_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update Date')),
                ('row_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='Row ID')),
                ('create_source', models.CharField(blank=True, choices=[('DJANGO', 'django'), ('WEB', 'web')], default='DJANGO', max_length=100, null=True, verbose_name='Create Source')),
                ('update_source', models.CharField(blank=True, choices=[('DJANGO', 'django'), ('WEB', 'web')], default='DJANGO', max_length=100, null=True, verbose_name='Update Source')),
                ('version', models.CharField(blank=True, max_length=100, null=True, verbose_name='Version')),
                ('accounting_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Accounting ID')),
                ('serial_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial ID')),
                ('registry_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registry ID')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region')),
                ('subregion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Region')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Name')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone')),
                ('operator', models.BooleanField(blank=True, default=True, verbose_name='Operator')),
                ('owner', models.BooleanField(blank=True, default=True, verbose_name='Owner')),
                ('purchaser', models.BooleanField(blank=True, default=True, verbose_name='Purchaser')),
                ('transporter', models.BooleanField(blank=True, default=True, verbose_name='Transporter')),
                ('service', models.BooleanField(blank=True, default=False, verbose_name='Service Provider')),
                ('company_ref', models.ManyToManyField(blank=True, to='db_models.Company', verbose_name='Parent Company')),
                ('last_updt_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last Update User')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Start Datetime')),
                ('end_datetime', models.DateTimeField(default=apps.db_models.models._base_domain.end_datetime, verbose_name='End Datetime')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
                ('name_de', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Short Name')),
                ('short_name_en', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Short Name')),
                ('short_name_ru', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Short Name')),
                ('short_name_de', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Short Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('operated', models.BooleanField(default=True, verbose_name='Operated')),
                ('last_updt_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update Date')),
                ('row_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='Row ID')),
                ('create_source', models.CharField(blank=True, choices=[('DJANGO', 'django'), ('WEB', 'web')], default='DJANGO', max_length=100, null=True, verbose_name='Create Source')),
                ('update_source', models.CharField(blank=True, choices=[('DJANGO', 'django'), ('WEB', 'web')], default='DJANGO', max_length=100, null=True, verbose_name='Update Source')),
                ('version', models.CharField(blank=True, max_length=100, null=True, verbose_name='Version')),
                ('accounting_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Accounting ID')),
                ('serial_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial ID')),
                ('registry_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registry ID')),
                ('latitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitude')),
                ('product', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product')),
                ('product_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product')),
                ('product_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product')),
                ('product_de', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Code')),
                ('direct_entry', models.BooleanField(default=False, verbose_name='Direct Entry')),
                ('scada', models.BooleanField(default=True, verbose_name='SCADA')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type')),
                ('type_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type')),
                ('type_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type')),
                ('type_de', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type')),
                ('day_start', models.DateTimeField(blank=True, null=True, verbose_name='Prod. Start')),
                ('battery_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_models.battery', verbose_name='Battery Ref.')),
                ('last_updt_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last Update User')),
            ],
            options={
                'verbose_name': 'battery',
                'verbose_name_plural': 'batteries',
                'ordering': ['name'],
            },
        ),
    ]
