# Generated by Django 3.2.10 on 2021-12-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battery',
            options={'ordering': ['name'], 'verbose_name': 'battery', 'verbose_name_plural': 'batteries'},
        ),
    ]
