# Generated by Django 3.2.10 on 2021-12-28 14:29

import apps.db_models.models._base_domain
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_domain',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='base_domain',
            name='end_datetime',
            field=models.DateTimeField(default=apps.db_models.models._base_domain.end_datetime, verbose_name='End Datetime'),
        ),
        migrations.AlterField(
            model_name='base_domain',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='base_domain',
            name='operated',
            field=models.BooleanField(default=True, verbose_name='Operated'),
        ),
        migrations.AlterField(
            model_name='base_domain',
            name='short_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='base_domain',
            name='start_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Start Datetime'),
        ),
    ]
