# Generated by Django 3.2.10 on 2021-12-28 14:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0002_auto_20211228_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_domain',
            name='accounting_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Accounting ID'),
        ),
        migrations.AlterField(
            model_name='base_domain',
            name='create_source',
            field=models.CharField(blank=True, choices=[('DJANGO', 'django'), ('WEB', 'web')], default='DJANGO', max_length=100, null=True, verbose_name='Create Source'),
        ),
        migrations.AlterField(
            model_name='base_domain',
            name='registry_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registry ID'),
        ),
        migrations.AlterField(
            model_name='base_domain',
            name='row_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='Row ID'),
        ),
        migrations.AlterField(
            model_name='base_domain',
            name='serial_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial ID'),
        ),
        migrations.AlterField(
            model_name='base_domain',
            name='update_source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Update Source'),
        ),
        migrations.AlterField(
            model_name='base_domain',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Version'),
        ),
    ]
