# Generated by Django 3.2.10 on 2021-12-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0002_battery_company_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='type',
        ),
        migrations.RemoveField(
            model_name='battery',
            name='type_de',
        ),
        migrations.RemoveField(
            model_name='battery',
            name='type_en',
        ),
        migrations.RemoveField(
            model_name='battery',
            name='type_ru',
        ),
        migrations.AddField(
            model_name='battery',
            name='battery_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Battery Type'),
        ),
        migrations.AddField(
            model_name='battery',
            name='battery_type_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Battery Type'),
        ),
        migrations.AddField(
            model_name='battery',
            name='battery_type_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Battery Type'),
        ),
        migrations.AddField(
            model_name='battery',
            name='battery_type_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Battery Type'),
        ),
    ]
