# Generated by Django 3.2.10 on 2021-12-28 16:34

import apps.db_models.models._base_domain
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0003_auto_20211228_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_domain',
            name='end_datetime_de',
            field=models.DateTimeField(default=apps.db_models.models._base_domain.end_datetime, null=True, verbose_name='End Datetime'),
        ),
        migrations.AddField(
            model_name='base_domain',
            name='end_datetime_en',
            field=models.DateTimeField(default=apps.db_models.models._base_domain.end_datetime, null=True, verbose_name='End Datetime'),
        ),
        migrations.AddField(
            model_name='base_domain',
            name='end_datetime_ru',
            field=models.DateTimeField(default=apps.db_models.models._base_domain.end_datetime, null=True, verbose_name='End Datetime'),
        ),
        migrations.AddField(
            model_name='base_domain',
            name='name_de',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='base_domain',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='base_domain',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='base_domain',
            name='short_name_de',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Short Name'),
        ),
        migrations.AddField(
            model_name='base_domain',
            name='short_name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Short Name'),
        ),
        migrations.AddField(
            model_name='base_domain',
            name='short_name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Short Name'),
        ),
        migrations.AddField(
            model_name='base_domain',
            name='start_datetime_de',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Start Datetime'),
        ),
        migrations.AddField(
            model_name='base_domain',
            name='start_datetime_en',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Start Datetime'),
        ),
        migrations.AddField(
            model_name='base_domain',
            name='start_datetime_ru',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Start Datetime'),
        ),
        migrations.AddField(
            model_name='company',
            name='country_de',
            field=models.CharField(blank=True, db_column='country_de', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='company',
            name='country_en',
            field=models.CharField(blank=True, db_column='country_en', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='company',
            name='country_ru',
            field=models.CharField(blank=True, db_column='country_ru', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='company',
            name='region_de',
            field=models.CharField(blank=True, db_column='region_de', max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='company',
            name='region_en',
            field=models.CharField(blank=True, db_column='region_en', max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='company',
            name='region_ru',
            field=models.CharField(blank=True, db_column='region_ru', max_length=100, null=True, verbose_name='Region'),
        ),
    ]
