# Generated by Django 3.2.10 on 2021-12-28 21:49

import apps.db_models.models._base_domain
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_models', '0004_auto_20211228_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Start Datetime')),
                ('end_datetime', models.DateTimeField(default=apps.db_models.models._base_domain.end_datetime, verbose_name='End Datetime')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Short Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('operated', models.BooleanField(default=True, verbose_name='Operated')),
                ('last_updt_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update Date')),
                ('row_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='Row ID')),
                ('create_source', models.CharField(blank=True, choices=[('DJANGO', 'django'), ('WEB', 'web')], default='DJANGO', max_length=100, null=True, verbose_name='Create Source')),
                ('update_source', models.CharField(blank=True, choices=[('DJANGO', 'django'), ('WEB', 'web')], default='DJANGO', max_length=100, null=True, verbose_name='Update Source')),
                ('version', models.CharField(blank=True, max_length=100, null=True, verbose_name='Version')),
                ('accounting_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Accounting ID')),
                ('serial_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial ID')),
                ('registry_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registry ID')),
                ('latitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitude')),
                ('product', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region')),
                ('subregion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Region')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('company_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_models.company', verbose_name='Company Ref.')),
                ('last_updt_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last Update User')),
            ],
            options={
                'verbose_name': 'field',
                'verbose_name_plural': 'fields',
                'ordering': ['name'],
            },
        ),
    ]
