# Generated by Django 3.2.10 on 2021-12-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0004_auto_20211228_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base_equip',
            options={'ordering': ['name'], 'verbose_name': 'base_equip', 'verbose_name_plural': 'base_equips'},
        ),
        migrations.AlterField(
            model_name='base_equip',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='base_equip',
            name='direct_entry',
            field=models.BooleanField(default=False, verbose_name='Direct Entry'),
        ),
        migrations.AlterField(
            model_name='base_equip',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='base_equip',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='base_equip',
            name='scada',
            field=models.BooleanField(default=True, verbose_name='SCADA'),
        ),
    ]
