# Generated by Django 3.2.10 on 2021-12-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0005_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='battery',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='battery',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='battery',
            name='subregion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Region'),
        ),
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='company',
            name='direct_entry',
            field=models.BooleanField(default=False, verbose_name='Direct Entry'),
        ),
        migrations.AddField(
            model_name='company',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='company',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='company',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='company',
            name='product_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='company',
            name='product_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='company',
            name='product_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='company',
            name='scada',
            field=models.BooleanField(default=True, verbose_name='SCADA'),
        ),
        migrations.AddField(
            model_name='field',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='field',
            name='direct_entry',
            field=models.BooleanField(default=False, verbose_name='Direct Entry'),
        ),
        migrations.AddField(
            model_name='field',
            name='scada',
            field=models.BooleanField(default=True, verbose_name='SCADA'),
        ),
    ]
