# Generated by Django 3.2.10 on 2021-12-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0005_auto_20211228_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battery',
            options={'ordering': ['name'], 'verbose_name': 'battery', 'verbose_name_plural': 'batteries'},
        ),
        migrations.AlterField(
            model_name='battery',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='direct_entry',
            field=models.BooleanField(default=False, verbose_name='Direct Entry'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='scada',
            field=models.BooleanField(default=True, verbose_name='SCADA'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Type'),
        ),
    ]
