# Generated by Django 3.2.10 on 2021-12-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0006_auto_20211228_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='city_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='battery',
            name='city_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='battery',
            name='city_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='battery',
            name='country_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='battery',
            name='country_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='battery',
            name='country_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='battery',
            name='region_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='battery',
            name='region_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='battery',
            name='region_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='battery',
            name='subregion_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Region'),
        ),
        migrations.AddField(
            model_name='battery',
            name='subregion_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Region'),
        ),
        migrations.AddField(
            model_name='battery',
            name='subregion_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Region'),
        ),
        migrations.AddField(
            model_name='field',
            name='city_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='field',
            name='city_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='field',
            name='city_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='field',
            name='country_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='field',
            name='country_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='field',
            name='country_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='field',
            name='name_de',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='field',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='field',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='field',
            name='product_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='field',
            name='product_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='field',
            name='product_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='field',
            name='region_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='field',
            name='region_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='field',
            name='region_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='field',
            name='short_name_de',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Short Name'),
        ),
        migrations.AddField(
            model_name='field',
            name='short_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Short Name'),
        ),
        migrations.AddField(
            model_name='field',
            name='short_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Short Name'),
        ),
        migrations.AddField(
            model_name='field',
            name='subregion_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Region'),
        ),
        migrations.AddField(
            model_name='field',
            name='subregion_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Region'),
        ),
        migrations.AddField(
            model_name='field',
            name='subregion_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Region'),
        ),
    ]
