# Generated by Django 3.2.10 on 2021-12-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0006_auto_20211228_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='company',
            name='operator',
            field=models.BooleanField(blank=True, default=True, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.BooleanField(blank=True, default=True, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='purchaser',
            field=models.BooleanField(blank=True, default=True, verbose_name='Purchaser'),
        ),
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='company',
            name='region_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='company',
            name='region_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='company',
            name='region_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='company',
            name='service',
            field=models.BooleanField(blank=True, default=False, verbose_name='Service Provider'),
        ),
        migrations.AlterField(
            model_name='company',
            name='subregion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Region'),
        ),
        migrations.AlterField(
            model_name='company',
            name='transporter',
            field=models.BooleanField(blank=True, default=True, verbose_name='Transporter'),
        ),
    ]
