# Generated by Django 3.2.10 on 2021-12-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0007_auto_20211228_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base_domain',
            name='end_datetime_de',
        ),
        migrations.RemoveField(
            model_name='base_domain',
            name='end_datetime_en',
        ),
        migrations.RemoveField(
            model_name='base_domain',
            name='end_datetime_ru',
        ),
        migrations.RemoveField(
            model_name='base_domain',
            name='start_datetime_de',
        ),
        migrations.RemoveField(
            model_name='base_domain',
            name='start_datetime_en',
        ),
        migrations.RemoveField(
            model_name='base_domain',
            name='start_datetime_ru',
        ),
        migrations.AddField(
            model_name='company',
            name='address_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='company',
            name='city_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='company',
            name='city_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='company',
            name='city_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_name_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Name'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Name'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Name'),
        ),
        migrations.AddField(
            model_name='company',
            name='subregion_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Region'),
        ),
        migrations.AddField(
            model_name='company',
            name='subregion_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Region'),
        ),
        migrations.AddField(
            model_name='company',
            name='subregion_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Region'),
        ),
    ]
