# Generated by Django 3.2.10 on 2021-12-28 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0007_auto_20211228_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='field_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_models.field', verbose_name='Field Ref.'),
        ),
    ]
