# Generated by Django 3.2.10 on 2021-12-28 23:53

import apps.db_models.models._base_domain
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_models', '0008_battery_field_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='battery',
            name='status_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='battery',
            name='status_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='battery',
            name='status_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='company',
            name='status_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='company',
            name='status_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='company',
            name='status_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='field',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='field',
            name='status_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='field',
            name='status_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='field',
            name='status_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Start Datetime')),
                ('end_datetime', models.DateTimeField(default=apps.db_models.models._base_domain.end_datetime, verbose_name='End Datetime')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Short Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('operated', models.BooleanField(default=True, verbose_name='Operated')),
                ('last_updt_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update Date')),
                ('row_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='Row ID')),
                ('create_source', models.CharField(blank=True, choices=[('DJANGO', 'django'), ('WEB', 'web')], default='DJANGO', max_length=100, null=True, verbose_name='Create Source')),
                ('update_source', models.CharField(blank=True, choices=[('DJANGO', 'django'), ('WEB', 'web')], default='DJANGO', max_length=100, null=True, verbose_name='Update Source')),
                ('version', models.CharField(blank=True, max_length=100, null=True, verbose_name='Version')),
                ('accounting_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Accounting ID')),
                ('serial_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial ID')),
                ('registry_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registry ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status')),
                ('product', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Code')),
                ('direct_entry', models.BooleanField(default=False, verbose_name='Direct Entry')),
                ('scada', models.BooleanField(default=True, verbose_name='SCADA')),
                ('latitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitude')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region')),
                ('subregion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Region')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('comp_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comp. Type')),
                ('disp_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Disp. Type')),
                ('inv_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='Inv. Method')),
                ('lift_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lift Type')),
                ('recovery', models.CharField(blank=True, max_length=100, null=True, verbose_name='Recovery')),
                ('bot_x', models.DecimalField(blank=True, decimal_places=8, max_digits=100, null=True, verbose_name='bot_x')),
                ('bot_y', models.DecimalField(blank=True, decimal_places=8, max_digits=100, null=True, verbose_name='bot_y')),
                ('completion_md', models.DecimalField(blank=True, decimal_places=8, max_digits=100, null=True, verbose_name='completion_md')),
                ('completion_tvd', models.DecimalField(blank=True, decimal_places=8, max_digits=100, null=True, verbose_name='completion_tvd')),
                ('api', models.CharField(blank=True, max_length=100, null=True, verbose_name='API')),
                ('cgr', models.DecimalField(blank=True, decimal_places=8, max_digits=100, null=True, verbose_name='CGR')),
                ('gor', models.DecimalField(blank=True, decimal_places=8, max_digits=100, null=True, verbose_name='GOR')),
                ('wgr', models.DecimalField(blank=True, decimal_places=8, max_digits=100, null=True, verbose_name='WGR')),
                ('wor', models.DecimalField(blank=True, decimal_places=8, max_digits=100, null=True, verbose_name='WOR')),
                ('gas_density', models.DecimalField(blank=True, decimal_places=8, max_digits=100, null=True, verbose_name='Gas Density')),
                ('gas_shrink', models.DecimalField(blank=True, decimal_places=8, max_digits=100, null=True, verbose_name='Gas Shrink')),
                ('ngl_frac', models.DecimalField(blank=True, decimal_places=8, max_digits=100, null=True, verbose_name='NGL Frac')),
                ('oil_density', models.DecimalField(blank=True, decimal_places=8, max_digits=100, null=True, verbose_name='Oil Density')),
                ('cond_theor_m', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cond Theo. Method')),
                ('gas_theor_m', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gas Theo. Method')),
                ('oil_theor_m', models.CharField(blank=True, max_length=100, null=True, verbose_name='Oil Theo. Method')),
                ('water_theor_m', models.CharField(blank=True, max_length=100, null=True, verbose_name='Water Theo. Method')),
                ('reservoir_phase', models.CharField(blank=True, max_length=15, null=True, verbose_name='Reservoir Phase')),
                ('reservoir_type', models.CharField(blank=True, max_length=15, null=True, verbose_name='Reservoir Type')),
                ('battery_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_models.battery', verbose_name='Battery Ref.')),
                ('field_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_models.field', verbose_name='Field Ref.')),
                ('last_updt_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last Update User')),
            ],
            options={
                'verbose_name': 'completion',
                'verbose_name_plural': 'completions',
                'ordering': ['name'],
            },
        ),
    ]
