# Generated by Django 3.2.10 on 2021-12-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0008_auto_20211228_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_domain',
            name='update_source',
            field=models.CharField(blank=True, choices=[('DJANGO', 'django'), ('WEB', 'web')], default='DJANGO', max_length=100, null=True, verbose_name='Update Source'),
        ),
    ]
