# Generated by Django 3.2.10 on 2021-12-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0009_auto_20211228_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='completion',
            name='city_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='completion',
            name='city_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='completion',
            name='city_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='completion',
            name='comp_type_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comp. Type'),
        ),
        migrations.AddField(
            model_name='completion',
            name='comp_type_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comp. Type'),
        ),
        migrations.AddField(
            model_name='completion',
            name='comp_type_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comp. Type'),
        ),
        migrations.AddField(
            model_name='completion',
            name='cond_theor_m_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cond Theo. Method'),
        ),
        migrations.AddField(
            model_name='completion',
            name='cond_theor_m_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cond Theo. Method'),
        ),
        migrations.AddField(
            model_name='completion',
            name='cond_theor_m_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cond Theo. Method'),
        ),
        migrations.AddField(
            model_name='completion',
            name='country_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='completion',
            name='country_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='completion',
            name='country_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='completion',
            name='disp_type_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Disp. Type'),
        ),
        migrations.AddField(
            model_name='completion',
            name='disp_type_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Disp. Type'),
        ),
        migrations.AddField(
            model_name='completion',
            name='disp_type_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Disp. Type'),
        ),
        migrations.AddField(
            model_name='completion',
            name='gas_theor_m_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gas Theo. Method'),
        ),
        migrations.AddField(
            model_name='completion',
            name='gas_theor_m_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gas Theo. Method'),
        ),
        migrations.AddField(
            model_name='completion',
            name='gas_theor_m_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gas Theo. Method'),
        ),
        migrations.AddField(
            model_name='completion',
            name='inv_method_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Inv. Method'),
        ),
        migrations.AddField(
            model_name='completion',
            name='inv_method_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Inv. Method'),
        ),
        migrations.AddField(
            model_name='completion',
            name='inv_method_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Inv. Method'),
        ),
        migrations.AddField(
            model_name='completion',
            name='lift_type_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lift Type'),
        ),
        migrations.AddField(
            model_name='completion',
            name='lift_type_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lift Type'),
        ),
        migrations.AddField(
            model_name='completion',
            name='lift_type_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lift Type'),
        ),
        migrations.AddField(
            model_name='completion',
            name='name_de',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='completion',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='completion',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='completion',
            name='oil_theor_m_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Oil Theo. Method'),
        ),
        migrations.AddField(
            model_name='completion',
            name='oil_theor_m_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Oil Theo. Method'),
        ),
        migrations.AddField(
            model_name='completion',
            name='oil_theor_m_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Oil Theo. Method'),
        ),
        migrations.AddField(
            model_name='completion',
            name='product_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='completion',
            name='product_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='completion',
            name='product_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='completion',
            name='recovery_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Recovery'),
        ),
        migrations.AddField(
            model_name='completion',
            name='recovery_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Recovery'),
        ),
        migrations.AddField(
            model_name='completion',
            name='recovery_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Recovery'),
        ),
        migrations.AddField(
            model_name='completion',
            name='region_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='completion',
            name='region_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='completion',
            name='region_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='completion',
            name='reservoir_phase_de',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Reservoir Phase'),
        ),
        migrations.AddField(
            model_name='completion',
            name='reservoir_phase_en',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Reservoir Phase'),
        ),
        migrations.AddField(
            model_name='completion',
            name='reservoir_phase_ru',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Reservoir Phase'),
        ),
        migrations.AddField(
            model_name='completion',
            name='reservoir_type_de',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Reservoir Type'),
        ),
        migrations.AddField(
            model_name='completion',
            name='reservoir_type_en',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Reservoir Type'),
        ),
        migrations.AddField(
            model_name='completion',
            name='reservoir_type_ru',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Reservoir Type'),
        ),
        migrations.AddField(
            model_name='completion',
            name='short_name_de',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Short Name'),
        ),
        migrations.AddField(
            model_name='completion',
            name='short_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Short Name'),
        ),
        migrations.AddField(
            model_name='completion',
            name='short_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Short Name'),
        ),
        migrations.AddField(
            model_name='completion',
            name='status_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='completion',
            name='status_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='completion',
            name='status_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='completion',
            name='subregion_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Region'),
        ),
        migrations.AddField(
            model_name='completion',
            name='subregion_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Region'),
        ),
        migrations.AddField(
            model_name='completion',
            name='subregion_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Region'),
        ),
        migrations.AddField(
            model_name='completion',
            name='water_theor_m_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Water Theo. Method'),
        ),
        migrations.AddField(
            model_name='completion',
            name='water_theor_m_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Water Theo. Method'),
        ),
        migrations.AddField(
            model_name='completion',
            name='water_theor_m_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Water Theo. Method'),
        ),
    ]
