# Generated by Django 3.2.8 on 2021-11-23 09:04

import dbmodels.models._base_domain
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base_domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True, db_column='start_datetime', default=django.utils.timezone.now, verbose_name='Datetime')),
                ('end_datetime', models.DateTimeField(db_column='end_datetime', default=dbmodels.models._base_domain.end_datetime, verbose_name='End Datetime')),
                ('name', models.CharField(db_column='name', max_length=100, unique=True, verbose_name='Name')),
                ('short_name', models.CharField(db_column='short_name', max_length=100, unique=True, verbose_name='Short Name')),
                ('active', models.BooleanField(db_column='active', default=True, verbose_name='Active')),
                ('operated', models.BooleanField(db_column='operated', default=True, verbose_name='Operated')),
                ('last_updt_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update Date')),
                ('row_id', models.UUIDField(db_column='row_id', default=uuid.uuid4, editable=False, null=True, verbose_name='Row ID')),
                ('create_source', models.CharField(blank=True, db_column='create_source', editable=False, max_length=100, null=True, verbose_name='Create Source')),
                ('update_source', models.CharField(blank=True, db_column='update_source', editable=False, max_length=100, null=True, verbose_name='Update Source')),
                ('version', models.CharField(blank=True, db_column='version', editable=False, max_length=100, null=True, verbose_name='Version')),
                ('accounting_id', models.CharField(blank=True, db_column='accounting_id', max_length=100, null=True, verbose_name='Accounting ID')),
                ('serial_id', models.CharField(blank=True, db_column='serial_id', max_length=100, null=True, verbose_name='Serial ID')),
                ('registry_id', models.CharField(blank=True, db_column='registry_id', max_length=100, null=True, verbose_name='Registry ID')),
            ],
        ),
        migrations.CreateModel(
            name='Base_equip',
            fields=[
                ('base_domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dbmodels.base_domain')),
                ('latitude', models.CharField(blank=True, db_column='latitude', max_length=100, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, db_column='longitude', max_length=100, null=True, verbose_name='Longitude')),
                ('code', models.CharField(blank=True, db_column='code', max_length=100, null=True, verbose_name='Code')),
                ('direct_entry', models.BooleanField(db_column='direct_entry', default=False, verbose_name='Manual')),
                ('scada', models.BooleanField(db_column='SCADA', default=True, verbose_name='SCADA')),
            ],
            bases=('dbmodels.base_domain',),
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('base_domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dbmodels.base_domain')),
                ('latitude', models.CharField(blank=True, db_column='latitude', max_length=100, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, db_column='longitude', max_length=100, null=True, verbose_name='Longitude')),
                ('day_start', models.DateTimeField(blank=True, null=True, verbose_name='Prod. Start')),
                ('code', models.CharField(blank=True, db_column='code', max_length=100, null=True, verbose_name='Code')),
                ('direct_entry', models.BooleanField(db_column='direct_entry', default=False, verbose_name='Manual')),
                ('scada', models.BooleanField(db_column='SCADA', default=True, verbose_name='SCADA')),
            ],
            bases=('dbmodels.base_domain',),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('base_domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dbmodels.base_domain')),
                ('contact_name', models.CharField(blank=True, db_column='contact_name', max_length=100, null=True, verbose_name='Contact Name')),
                ('address', models.CharField(blank=True, db_column='address', max_length=100, null=True, verbose_name='Address')),
                ('email', models.CharField(blank=True, db_column='email', max_length=100, null=True, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=100, null=True, verbose_name='Phone')),
                ('operator', models.BooleanField(blank=True, db_column='operator', default=True, verbose_name='Operator')),
                ('owner', models.BooleanField(blank=True, db_column='owner', default=True, verbose_name='Owner')),
                ('purchaser', models.BooleanField(blank=True, db_column='purchaser', default=True, verbose_name='Purchaser')),
                ('transporter', models.BooleanField(blank=True, db_column='transporter', default=True, verbose_name='Transporter')),
                ('service', models.BooleanField(blank=True, db_column='service', default=False, verbose_name='Service Provider')),
            ],
            bases=('dbmodels.base_domain',),
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('base_domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dbmodels.base_domain')),
                ('latitude', models.CharField(blank=True, db_column='latitude', max_length=100, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, db_column='longitude', max_length=100, null=True, verbose_name='Longitude')),
            ],
            bases=('dbmodels.base_domain',),
        ),
    ]
