# Generated by Django 3.2.8 on 2021-11-14 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_auto_20211110_1416'),
        ('dbmodels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='type_product',
            name='last_updt_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last Update User'),
        ),
        migrations.AddField(
            model_name='type_product',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dbmodels.type_product', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='type_battery',
            name='last_updt_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last Update User'),
        ),
        migrations.AddField(
            model_name='type_battery',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dbmodels.type_battery', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='base_domain',
            name='last_updt_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last Update User'),
        ),
        migrations.AddField(
            model_name='field',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='field',
            name='company_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmodels.company', verbose_name='Company Ref.'),
        ),
        migrations.AddField(
            model_name='field',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='field',
            name='region',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='field',
            name='subregion',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.subregion', verbose_name='Sub-Region'),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='company',
            name='parent',
            field=models.ManyToManyField(blank=True, to='dbmodels.Company', verbose_name='Parent Company'),
        ),
        migrations.AddField(
            model_name='company',
            name='region',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='company',
            name='subregion',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.subregion', verbose_name='Sub-Region'),
        ),
        migrations.AddField(
            model_name='battery',
            name='field_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmodels.field', verbose_name='Field Ref.'),
        ),
        migrations.AddField(
            model_name='battery',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmodels.type_product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='battery',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmodels.type_battery', verbose_name='Type'),
        ),
    ]
