# Generated by Django 3.2.8 on 2021-11-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_uom',
            name='catalog_name',
            field=models.CharField(blank=True, db_column='catalog_name', max_length=100, verbose_name='Catalog Name'),
        ),
        migrations.AlterField(
            model_name='base_uom',
            name='conversion_type',
            field=models.CharField(blank=True, db_column='conversion_type', max_length=100, null=True, verbose_name='Conversion Type'),
        ),
        migrations.AlterField(
            model_name='base_uom',
            name='dimension_class',
            field=models.CharField(db_column='dimension_class', max_length=100, verbose_name='Dimenstion Class'),
        ),
        migrations.AlterField(
            model_name='base_uom',
            name='metric_system',
            field=models.CharField(blank=True, db_column='metric_system', max_length=100, null=True, verbose_name='Metric System'),
        ),
    ]
