# Generated by Django 3.2.8 on 2021-11-20 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='density_uom',
            field=models.ForeignKey(blank=True, db_column='density_uom', null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmodels.uom_set', verbose_name='Density UOM'),
        ),
    ]
