# Generated by Django 3.2.8 on 2021-11-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='parent',
            field=models.ManyToManyField(blank=True, to='dbmodels.Company'),
        ),
    ]
