# Generated by Django 3.2.8 on 2021-11-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0002_auto_20211116_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base_uom',
            name='baseUomId',
        ),
        migrations.AddField(
            model_name='base_uom',
            name='base_uom_id',
            field=models.CharField(db_column='base_uom_id', default=0, max_length=100, verbose_name='Base UOM ID'),
            preserve_default=False,
        ),
    ]
