# Generated by Django 3.2.8 on 2021-11-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0002_alter_company_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='service',
            field=models.BooleanField(blank=True, db_column='service', default=False),
        ),
    ]
