# Generated by Django 3.2.8 on 2021-11-18 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0003_auto_20211118_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom_set',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmodels.uom_property'),
        ),
    ]
