# Generated by Django 3.2.8 on 2021-11-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0003_auto_20211116_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_uom',
            name='dimension_class',
            field=models.CharField(db_column='dimension_class', max_length=100, null=True, verbose_name='Dimenstion Class'),
        ),
    ]
