# Generated by Django 3.2.8 on 2021-11-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0004_alter_uom_set_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uom_base',
            old_name='property_class',
            new_name='property',
        ),
    ]
