# Generated by Django 3.2.8 on 2021-11-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0004_alter_base_uom_dimension_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_uom',
            name='code_name',
            field=models.CharField(db_column='code_name', max_length=100, null=True, verbose_name='Code Name'),
        ),
    ]
