# Generated by Django 3.2.8 on 2021-11-18 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0005_rename_property_class_uom_base_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom_set',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmodels.uom_property', verbose_name='Property Class'),
        ),
    ]
