# Generated by Django 3.2.8 on 2021-11-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0006_alter_uom_set_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='location',
        ),
        migrations.RemoveField(
            model_name='uom',
            name='base_id',
        ),
        migrations.RemoveField(
            model_name='uom',
            name='property',
        ),
        migrations.RemoveField(
            model_name='uom2',
            name='base_uom_id',
        ),
        migrations.RemoveField(
            model_name='uom2',
            name='propertly_class',
        ),
        migrations.RenameField(
            model_name='uom_base',
            old_name='dimension_class',
            new_name='dimension',
        ),
        migrations.DeleteModel(
            name='BaseUOMID',
        ),
        migrations.DeleteModel(
            name='PropertyClass',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='UOM',
        ),
        migrations.DeleteModel(
            name='UOM2',
        ),
    ]
