# Generated by Django 3.2.8 on 2021-11-20 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbmodels', '0007_auto_20211119_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_text', models.CharField(db_column='code_text', max_length=100, unique=True, verbose_name='Code Name')),
                ('code', models.CharField(db_column='code', max_length=100, unique=True, verbose_name='Code')),
                ('last_updt_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update Date')),
                ('row_id', models.UUIDField(db_column='row_id', default=uuid.uuid4, editable=False, null=True, verbose_name='Row ID')),
                ('create_source', models.CharField(blank=True, db_column='create_source', editable=False, max_length=100, null=True, verbose_name='Create Source')),
                ('update_source', models.CharField(blank=True, db_column='update_source', editable=False, max_length=100, null=True, verbose_name='Update Source')),
                ('version', models.CharField(blank=True, db_column='version', editable=False, max_length=100, null=True, verbose_name='Version')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('last_updt_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last Update User')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dbmodels.type_status', verbose_name='Parent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
