version: "3.9"

services:
    redis:
        restart: always
        image: redis:5-alpine
        volumes:
            - redis_data:/app
        # expose:
        #     - 6379
        ports:
            - "6379:6379"
        networks:
            - ligeiaai
    postgres:
        restart: always
        image: postgres:13.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASS}
            - POSTGRES_DB=${PG_DB}
        ports:
            - "5434:5432"
        networks:
            - ligeiaai

    # pgadmin:
    #     restart: always
    #     container_name: pgadmin4_container
    #     image: dpage/pgadmin4        
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: admin@admin.com
    #         PGADMIN_DEFAULT_PASSWORD: manager
    #     ports:
    #         - "5050:80"
    django:
        restart: always
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        command: /start
        volumes:
            - .:/app
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        env_file:
            - .env
        # environment:
        #     PG_DB: $PG_DB
        #     PG_USER: $PG_USER
        #     PG_PASS: $PG_PASS
        #     PG_HOST: $PG_HOST
        #     PG_PORT: $PG_PORT
        depends_on:
            - postgres
            - redis
        networks:
            - ligeiaai        
networks:
    ligeiaai:
        driver: bridge
volumes:
    postgres_data:
    static_volume:
    media_volume:
    redis_data:
