version: '3'

services:
    nginx:
        restart: always
        image: nginx:latest
        # image: nginx:1.11.6-alpine
    postgres:
        restart: always
        image: postgres:latest
        #image: postgres:10.1
        expose:
            - 5432
        environment:
            POSTGRES_USER: db_admin
            POSTGRES_PASSWORD: manager
            POSTGRES_DB: db_core
        ports:
            - 5434:5432
    pgadmin:
        restart: always
        container_name: pgadmin4_container
        image: dpage/pgadmin4        
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: manager
        ports:
            - "5050:80"
    django:
        restart: always
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        volumes:
            - .:/django
    web:
        restart: always
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        volumes:
            - .:/django
    redis:
        restart: always
        image: redis:latest
        volumes:
            - .:/django
        expose:
            - 6379