version: "3.9"

services:
    redis:
        restart: always
        image: redis:5-alpine
        volumes:
            - .:/app
        # expose:
        #     - 6379
        ports:
            - "6379:6379"
        networks:
            - ligeiaai
    postgres:
        restart: always
        image: postgres:13.0-alpine
        volumes:
            - .:/app
        environment:
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASS}
            - POSTGRES_DB=${PG_DB}
        ports:
            - "5434:5432"
        networks:
            - ligeiaai

    # pgadmin:
    #     restart: always
    #     container_name: pgadmin4_container
    #     image: dpage/pgadmin4        
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: admin@admin.com
    #         PGADMIN_DEFAULT_PASSWORD: manager
    #     ports:
    #         - "5050:80"
    django:
        restart: always
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        command: /start
        volumes:
            - .:/app
        env_file:
            - .env
        depends_on:
            - postgres
            - redis
        ports:
            - "8000:8000" 
        networks:
            - ligeiaai

networks:
    ligeiaai:
        driver: bridge
# volumes:
#     django_data:

