version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/env/prod/db/.env

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
      command: python manage.py runserver 0.0.0.0:8000
      # command: gunicorn nordalbackend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/application/web/staticfiles
      - media_volume:/home/application/web/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./app/env/prod/.env
    depends_on:
      - db