version: "3.9"

services:
  web:
    build: 
      context: ./IEFPP
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./IEFPP/env/prod/.env
    volumes:
      - static_volume:/home/application/web/staticfiles
      - media_volume:/home/application/web/mediafiles
#     depends_on:
#       - db
#   db:
#     image: postgres
#     ports:
#       - 5432:5432
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     env_file:
#       - ./IEFPP/env/prod/db/.env

volumes:
  # postgres_data:
  static_volume:
  media_volume: