version: "3.8"
services:
  # web:
  #   restart: on-failure
  #   build:
  #     context: .
  #     dockerfile: ./docker/local/web/Dockerfile
  #   volumes:
  #     - .:/web
  #   # - /web/node_modules
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - net
  django:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./dockerfile/local/django/Dockerfile
    command: /start
    env_file:
      - .env
    volumes:
      - .:/django
      # - static_volume:/django/staticfiles
      # - media_volume:/django/mediafiles
    depends_on:
      - redis
      - postgres
      - es
    ports:
      - "8000:8000"
    networks:
      - net

  es:
    image: elasticsearch:8.4.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  postgres:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    # env_file:
    #   - .env
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
    ports:
      - "5434:5432"
    networks:
      - net
  pgadmin:
    restart: on-failure
    image: dpage/pgadmin4:latest
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASS}
    ports:
      - "5050:80"
    networks:
      - net
  redis:
    restart: on-failure
    image: redis:latest
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - net
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - net

  broker:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: "true"
      CONFLUENT_SUPPORT_CUSTOMER_ID: "anonymous"
      KAFKA_JMX_HOSTNAME: localhost
    networks:
      - net

networks:
  net:
    driver: bridge
volumes:
  postgres-data: null
  pgadmin-data: null
  redis-data: null
  mongodb-data: null
  zookeeper_data:
    driver: local
  broker_data:
    driver: local
  # celery_worker:
  #   restart: on-failure
  #   build:
  #     context: .
  #     dockerfile: ./docker/local/django/Dockerfile
  #   command: /start-celeryworker
  #   volumes:
  #     - .:/django
  #   env_file:
  #     - .env
  #   depends_on:
  #     - redis
  #     - postgres
  #   networks:
  #     - net
  # flower:
  #   build:
  #     context: .
  #     dockerfile: ./docker/local/django/Dockerfile
  #   command: /start-flower
  #   volumes:
  #     - .:/django
  #   env_file:
  #     - .env
  #   ports:
  #     - "5557:5555"
  #   depends_on:
  #     - redis
  #     - postgres
  #   networks:
  #     - net

  # # mongodb:
  # #   restart: unless-stopped
  # #   image: mongo:latest
  # #   volumes:
  # #     - mongodb-data:/data/db
  # #     - mongodb-data:/data/configdb
  # #   environment:
  # #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
  # #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
  # #   ports:
  # #     - "27017:27017"
  # #   networks:
  # #     - net
