version: '3'

services:
    redis:
        extends:
            file: docker-common.yml
            service: redis
        ports:
            - 6379:6379
    nginx:
        extends:
            file: docker-common.yml
            service: nginx
        ports:
            - 8000:8000
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - backend
    postgres:
        extends:
            file: docker-common.yml
            service: postgres
    backend:
        environment:
            DB_NAME: $POSTGRES_DB
            DB_USER: $POSTGRES_USER
            DB_PASS: $POSTGRES_PASS
            DB_HOST: $POSTGRES_HOST
            DB_PORT: $POSTGRES_PORT
            DEBUG: $DEBUG
            REDIS_URI: $REDIS_URI
        extends:
            file: docker-common.yml
            service: django
        links:
            - postgres
            - pgadmin
            - redis
        entrypoint:
            - /django-entrypoint.sh
        expose:
            - 8000
    frontend:
        extends:
            file: docker-common.yml
            service: web
        links:
            - backend
        entrypoint:
            - /web-entrypoint.sh
