version: "3.8"

services:
  app:
    restart: always
    container_name: ligeia_mare
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        # Update 'VARIANT' to pick a version of Python: 3, 3.10, 3.9, 3.8, 3.7, 3.6
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        # VARIANT: 3.10-buster
        # Optional Node.js version to install
        NODE_VERSION: "lts/*"
    command: /start
    volumes:
      - ..:/app
      # - static_volume:/django/staticfiles
      # - media_volume:/django/mediafiles
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      # - redis
    network_mode: service:postgres

  postgres:
    restart: always
    container_name: ligeia_mare
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
    ports:
      - "5434:5432"
    networks:
      - net
  # redis:
  #   restart: always
  #   container_name: ligeia_mare
  #   image: redis:5-alpine
  #   volumes:
  #     - redis_data:/data
  #   expose:
  #     - "6379"
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - ligeiaai
  # pgadmin:
  #   restart: always
  #   container_name: ligeia_pgadmin4
  #   image: dpage/pgadmin4
  #   volumes:
  #     - postgres_data:/var/lib/pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: manager
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - ligeiaai

networks:
  net:
    driver: bridge
volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
