version: "3.9"

services:
    redis:
        restart: always
        image: redis:latest
        volumes:
            - .:/django
        expose:
            - 6379
        # extends:
        #     # file: docker-common.yml
        #     service: redis
        ports:
            - 6379:6379
    # nginx:
    #     restart: always
    #     image: nginx:latest  
    #     # extends:
    #     #     # file: docker-common.yml
    #     #     service: nginx
    #     ports:
    #         - 8000:8000
    #     volumes:
    #         - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        # volumes_from:
        #     - backend
    postgres:
        restart: always
        image: postgres:latest    
        expose:
            - 5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASS}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "5434:5432"
        # extends:
        #     # file: docker-common.yml
        #     service: postgres
    # pgadmin:
    #     restart: always
    #     container_name: pgadmin4_container
    #     image: dpage/pgadmin4        
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: admin@admin.com
    #         PGADMIN_DEFAULT_PASSWORD: manager
    #     ports:
    #         - "5050:80"
    backend:
        restart: always
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        volumes:
            - .:/backend
        environment:
            # DB_NAME: ${POSTGRES_DB}
            # DB_USER: ${POSTGRES_USER}
            # DB_PASS: ${POSTGRES_PASS}
            DEBUG: ${DEBUG}
            REDIS_URI: ${REDIS_URI}
        # extends:
        #     # file: docker-common.yml
        #     service: backend
        links:
            - postgres
            - redis
        entrypoint:
            - /django-entrypoint.sh
        expose:
            - 8000
    # frontend:
    #     extends:
    #         file: docker-common.yml
    #         service: web
    #     links:
    #         - backend
    #     entrypoint:
    #         - /web-entrypoint.sh
