//-----------Auth---------------------
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL';
export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS';
export const FACEBOOK_AUTH_FAIL = 'FACEBOOK_AUTH_FAIL';
export const LOGOUT = 'LOGOUT';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
export const GITHUB_AUTH_FAIL = 'GITHUB_AUTH_FAIL';
export const GITHUB_AUTH_SUCCESS = 'GITHUB_AUTH_SUCCESS';

//-----------Error---------------------
export const ADD_ERROR_SUCCESS = 'ADD_ERROR_SUCCESS';
export const ADD_ERROR_FAIL = 'ADD_ERROR_FAIL';
export const CLEAN_ERROR_SUCCESS = 'CLEAN_ERROR_SUCCESS';
export const CLEAN_ERROR_FAIL = 'CLEAN_ERROR_FAIL';


//-----------Type - item - link Editor---------------------
export const ADD_DATE_BREAK_COLUMN = "ADD_DATE_BREAK_COLUMN";
export const DELETE_DATE_BREAK_COLUMN = "DELETE_DATE_BREAK_COLUMN";
export const ADD_ROW = "ADD_ROW";
export const EDIT_ROW = "EDIT_ROW";
export const SAVE_ITEM = "SAVE_ITEM";
export const ADD_ITEM_TYPE = "ADD_ITEM_TYPE";
export const LOAD_TREEVIEW_ITEM = "LOAD_TREEVIEW_ITEM";
export const SET_SELECTED_ITEM = "SET_SELECTED_ITEM";
export const CLEAN_DATA_GRID = "CLEAN_DATA_GRID";
export const IS_CHANGED_HANDLER = "IS_CHANGED_HANDLER";
export const ADD_COLUMN = "ADD_COLUMN";
export const SET_LOADING = "SET_LOADING";
export const CLEAN_ROWS = "CLEAN_ROWS";
export const LOAD_LINK_EDITOR = "LOAD_LINK_EDITOR";
export const LOAD_LINKS = "LOAD_LINKS";
export const UPDATE_LINKS_VALUE = "UPDATE_LINKS_VALUE";
export const SET_LINK_ACTIVE = "SET_LINK_ACTIVE";
export const CLEAN_ALL_DATAGRID = "CLEAN_ALL_DATAGRID";
export const CLEAN_ALL_TREEMENU = "CLEAN_ALL_TREEMENU";
export const CLEAN_ALL_LINK_EDITOR = "CLEAN_ALL_LINK_EDITOR";
export const LOAD_CHECKLIST = "LOAD_CHECKLIST";
export const LOAD_LINK_EDITOR_SCHEMA = "LOAD_LINK_EDITOR_SCHEMA";
export const SET_CHECKED_ITEMS = "SET_CHECKED_ITEMS";
export const CLEAN_COMPANY_CHECKED_LIST = "CLEAN_COMPANY_CHECKED_LIST";
export const CLEAN_CHANGED_LIST_LINK_EDITOR = "CLEAN_CHANGED_LIST_LINK_EDITOR";
export const LOAD_LINK_EDITOR_SCHEMA_FROM_TYPE = "LOAD_LINK_EDITOR_SCHEMA_FROM_TYPE";

//-----------TAGS-----------------------
export const SELECT_TREEVIEW_ITEM_TAGS = "SELECT_TREEVIEW_ITEM_TAGS";
export const LOAD_TAGS_LABEL = "LOAD_TAGS_LABEL";
export const SET_TAG_SAVE_VALUES = "SET_TAG_SAVE_VALUES";
export const CLEAN_ALL_TAGS = "CLEAN_ALL_TAGS";
export const CLEAN_ALL_TREEVIEW_TAGS = "CLEAN_ALL_TREEVIEW_TAGS";
export const TOGGLE_CHANGES_TAGS = "TOGGLE_CHANGES_TAGS";
export const LOAD_TREEVIEW_TAGS = "LOAD_TREEVIEW_TAGS";
export const FILL_SAVE_VALUES_TAGS = "FILL_SAVE_VALUES_TAGS";
export const LOAD_ITEMS_FOR_TAGLINKS = "LOAD_ITEMS_FOR_TAGLINKS";


//-----------Code List-------------------
export const LOAD_TREEVIEW_ITEM_CODELIST = "LOAD_TREEVIEW_ITEM_CODELIST";
export const SELECT_TREEVIEW_ITEM_CODELIST = "SELECT_TREEVIEW_ITEM_CODELIST";
export const LOAD_DATAGRID_ROW_CODELIST = "LOAD_DATAGRID_ROW_CODELIST";
export const ON_CHANGE_CODELIST_CELL = "ON_CHANGE_CODELIST_CELL";
export const CLEAN_AFTER_SAVE = "CLEAN_AFTER_SAVE";
export const SET_SELECTED_ROWS = "SET_SELECTED_ROWS";
export const CLEAN_SELECTED_ROWS = "CLEAN_SELECTED_ROWS";
export const REFRESH_ROWS_CODELIST = "REFRESH_ROWS_CODELIST";
export const REFRESH_DELETECHILD_CODELIST = "REFRESH_DELETECHILD_CODELIST";
export const ADD_NEW_CHILD_CODELIST = "ADD_NEW_CHILD_CODELIST";
export const CLEAN_ALL_DATAGRID_CODELIST = "CLEAN_ALL_DATAGRID_CODELIST";
export const CLEAN_TREEVIEW_SELECT_CODELIST = "CLEAN_TREEVIEW_SELECT_CODELIST";
export const LOAD_FILTERED_TREEVIEW_ITEM_CODELIST = "LOAD_FILTERED_TREEVIEW_ITEM_CODELIST";
export const SET_FILTERED_LAYER_NAME_CODELIST = "SET_FILTERED_LAYER_NAME_CODELIST";

//------------Hıghchart---------------------
export const SET_CHART_TYPE_OVERVIEW = "SET_CHART_TYPE_OVERVIEW";

//------------Drawer Menu-----------------
export const SET_SELECTED_DRAWER_ITEM = "SET_SELECTED_DRAWER_ITEM";
export const TOGGLE_DRAWER_MENU = "TOGGLE_DRAWER_MENU";
// export const MOUSE_ENTER_DRAWER = "MOUSE_ENTER_DRAWER";
// export const MOUSE_LEAVE_DRAWER = "MOUSE_LEAVE_DRAWER";
export const LOAD_DRAWER_MENU = "LOAD_DRAWER_MENU";

//-----------Project ---------------------
export const CHANGE_VALUE_PROJECT = "CHANGE_VALUE_PROJECT";
export const CLEAN_VALUE_PROJECT = "CLEAN_VALUE_PROJECT";


//------------TYPE -------------------
export const SET_ROW_DATAGRID_TYPE = "SET_ROW_DATAGRID_TYPE";
export const SET_CHANGE_TYPE_VALUE_CELL_TAG = "SET_CHANGE_TYPE_VALUE_CELL_TAG";
export const LAOD_TREEVIEW_TYPE = "LAOD_TREEVIEW_TYPE";
export const SELECT_TREEVIEW_ITEM_TYPE = "SELECT_TREEVIEW_ITEM_TYPE";
export const AFTER_GO_INDEX_TYPE = "AFTER_GO_INDEX_TYPE";
export const SET_PROPERTY_ROW = "SET_PROPERTY_ROW";
export const CHANGE_SELECTED_ROW_PROPERTY = "CHANGE_SELECTED_ROW_PROPERTY";
export const SET_CHANGE_PROPERTY_VALUE_CELL_TAG = "SET_CHANGE_PROPERTY_VALUE_CELL_TAG";
export const DELETE_SELECTED_ITEM_PROPERTY = "DELETE_SELECTED_ITEM_PROPERTY";
export const ADD_NEW_PROPERTY = "ADD_NEW_PROPERTY";
export const LOAD_FILTERED_TREEVIEW_ITEM_TYPE = "LOAD_FILTERED_TREEVIEW_ITEM_TYPE";
export const SET_FILTERED_LAYER_NAME_TYPE = "SET_FILTERED_LAYER_NAME_TYPE"
export const CLEAN_ALL_DATAGRID_TYPE = "CLEAN_ALL_DATAGRID_TYPE"

//------------TREEVIEW -------------------------
export const LOAD_TREEVIEW_ITEMS = "LOAD_TREEVIEW_ITEM";
export const SELECT_TREEVIEW_ITEM = "SELECT_TREEVIEW_ITEM";
export const CLEAN_TREEVIEW_SELECT = "CLEAN_TREEVIEW_SELECT";
export const LOAD_FILTERED_TREEVIEW_ITEM = "LOAD_FILTERED_TREEVIEW_ITEM";
export const SET_FILTERED_LAYER_NAME = "SET_FILTERED_LAYER_NAME";
export const CLEAN_TREEVIEW = "CLEAN_TREEVIEW";


//-------------CONFIRMATION-------------------
export const SET_IS_ACTIVE_CONFIRMATION = "SET_IS_ACTIVE_CONFIRMATION";
export const SET_SAVE_FUNCTION_CONFIRMATION = "SET_SAVE_FUNCTION_CONFIRMATION";
export const SET_BODY_CONFIRMATION = "SET_BODY_CONFIRMATION";
export const SET_TITLE_CONFIRMATION = "SET_TITLE_CONFIRMATION";
export const SET_GO_FUNCTION_CONFIRMATION = "SET_GO_FUNCTION_CONFIRMATION";
export const SET_IS_OPEN_CONFIRMATION = "SET_IS_OPEN_CONFIRMATION";
export const SET_CLEAN_CONFIRMATION = "SET_CLEAN_CONFIRMATION";