modelApp = [
    "apps.code_list",
    "apps.item",
    "apps.item_link",
    "apps.type_property",
    "apps.type_link",
    "apps.item_property",
    "apps.type",
    "apps.resource_list",
    "apps.type_uom",
    "apps.item_version",
    "apps.layer",
    "apps.tags",
    "apps.notifications",
    "apps.uom",
    "apps.websocket",
    "apps.uom_base_unit",
    ]
