modelApp = [
    "apps.code_list",
    "apps.item",
    "apps.item_link",
    "apps.type_property",
    "apps.type_link",
    "apps.item_property",
    "apps.type",
    "apps.resources_types",
    "apps.type_uom",
    "apps.item_version",
    "apps.layer",
    "apps.tags",
    "apps.notifications",
    "apps.websocket",
    "apps.uoms",
    "apps.uom_base_unit",
    "apps.calculated_tag",
    "apps.bi_widgets",
    "apps.bi_widget_property",
    "apps.bi_layouts",
    "apps.bi_widget_type",
    "apps.bi_dashbord",
    "apps.roles_type",
    "apps.roles_property",
    "apps.roles",
    "apps.resources_drawer",
    
]
#     "apps.uom",
