# Generated by Django 4.1.8 on 2023-04-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bi_widget_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WIDGET_TYPE', models.CharField(db_index=True, max_length=500, null=True)),
                ('properties', models.JSONField(null=True)),
            ],
        ),
    ]
