# Generated by Django 3.2.8 on 2021-11-05 08:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base_codelist',
            fields=[
                ('item_id', models.UUIDField(db_column='item_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updt_user', models.CharField(blank=True, db_column='last_updt_user', max_length=15)),
                ('last_updt_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('culture', models.CharField(blank=True, db_column='culture', max_length=15, null=True, unique=True)),
                ('row_id', models.UUIDField(db_column='row_id', default=uuid.uuid4, editable=False)),
                ('update_source', models.CharField(blank=True, db_column='update_source', max_length=15)),
                ('version', models.CharField(blank=True, db_column='version', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Base_domain',
            fields=[
                ('start_datetime', models.DateTimeField(db_column='start_datetime')),
                ('end_datetime', models.DateTimeField(blank=True, db_column='end_datetime')),
                ('name', models.CharField(db_column='name', max_length=30, unique=True)),
                ('short_name', models.CharField(blank=True, db_column='short_name', max_length=30, unique=True)),
                ('operated', models.BooleanField(db_column='operated', default=True)),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('item_id', models.UUIDField(db_column='item_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updt_user', models.CharField(blank=True, db_column='last_updt_user', max_length=15)),
                ('last_updt_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('culture', models.CharField(blank=True, db_column='culture', max_length=15, null=True, unique=True)),
                ('row_id', models.UUIDField(db_column='row_id', default=uuid.uuid4, editable=False)),
                ('update_source', models.CharField(blank=True, db_column='update_source', max_length=15)),
                ('version', models.CharField(blank=True, db_column='version', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Base_equip',
            fields=[
                ('base_domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base_domain')),
                ('accounting_id', models.CharField(blank=True, db_column='accounting_id', max_length=15, null=True)),
                ('fdc_id', models.CharField(blank=True, db_column='fdc_id', max_length=15, null=True)),
                ('registry_id', models.CharField(blank=True, db_column='registry_id', max_length=15, null=True)),
            ],
            bases=('core.base_domain',),
        ),
        migrations.CreateModel(
            name='Type_battery',
            fields=[
                ('base_codelist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base_codelist')),
                ('code_text', models.CharField(db_column='code_text', max_length=15, unique=True)),
                ('code', models.CharField(db_column='code', max_length=15, unique=True)),
                ('parent', models.CharField(blank=True, db_column='parent', max_length=15, null=True, unique=True)),
            ],
            bases=('core.base_codelist',),
        ),
        migrations.CreateModel(
            name='Type_country',
            fields=[
                ('base_codelist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base_codelist')),
                ('code_text', models.CharField(db_column='code_text', max_length=15, unique=True)),
                ('code', models.CharField(db_column='code', max_length=15, unique=True)),
                ('parent', models.CharField(blank=True, db_column='parent', max_length=15, null=True, unique=True)),
            ],
            bases=('core.base_codelist',),
        ),
        migrations.CreateModel(
            name='Type_county',
            fields=[
                ('base_codelist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base_codelist')),
                ('code_text', models.CharField(db_column='code_text', max_length=15, unique=True)),
                ('code', models.CharField(db_column='code', max_length=15, unique=True)),
                ('parent', models.CharField(blank=True, db_column='parent', max_length=15, null=True, unique=True)),
            ],
            bases=('core.base_codelist',),
        ),
        migrations.CreateModel(
            name='Type_product',
            fields=[
                ('base_codelist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base_codelist')),
                ('code_text', models.CharField(db_column='code_text', max_length=15, unique=True)),
                ('code', models.CharField(db_column='code', max_length=15, unique=True)),
                ('parent', models.CharField(blank=True, db_column='parent', max_length=15, null=True, unique=True)),
            ],
            bases=('core.base_codelist',),
        ),
        migrations.CreateModel(
            name='Type_pump',
            fields=[
                ('base_codelist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base_codelist')),
                ('code_text', models.CharField(db_column='code_text', max_length=15, unique=True)),
                ('code', models.CharField(db_column='code', max_length=15, unique=True)),
                ('parent', models.CharField(blank=True, db_column='parent', max_length=15, null=True, unique=True)),
            ],
            bases=('core.base_codelist',),
        ),
        migrations.CreateModel(
            name='Type_state',
            fields=[
                ('base_codelist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base_codelist')),
                ('code_text', models.CharField(db_column='code_text', max_length=15, unique=True)),
                ('code', models.CharField(db_column='code', max_length=15, unique=True)),
                ('parent', models.CharField(blank=True, db_column='parent', max_length=15, null=True, unique=True)),
            ],
            bases=('core.base_codelist',),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('base_domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base_domain')),
                ('contact_name', models.CharField(blank=True, db_column='contact_name', max_length=15, null=True)),
                ('address', models.CharField(blank=True, db_column='address', max_length=15, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=15, null=True)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=15, null=True)),
                ('operator', models.BooleanField(blank=True, db_column='operator', default=True)),
                ('owner', models.BooleanField(blank=True, db_column='owner', default=True)),
                ('purchaser', models.BooleanField(blank=True, db_column='purchaser', default=True)),
                ('transporter', models.BooleanField(blank=True, db_column='transporter', default=True)),
                ('company_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.type_country')),
            ],
            bases=('core.base_domain',),
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('base_domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base_domain')),
                ('latitude', models.CharField(blank=True, db_column='latitude', max_length=15, null=True)),
                ('longitude', models.CharField(blank=True, db_column='longitude', max_length=15, null=True)),
                ('day_start', models.DateTimeField(blank=True, null=True)),
                ('product', models.CharField(blank=True, db_column='type_product', max_length=15, null=True)),
                ('code', models.CharField(blank=True, db_column='code', max_length=15, null=True)),
                ('direct_entry', models.BooleanField(db_column='direct_entry', default=False)),
                ('scada', models.BooleanField(db_column='SCADA', default=True)),
                ('accounting_id', models.CharField(blank=True, db_column='accounting_id', max_length=15, null=True)),
                ('fdc_id', models.CharField(blank=True, db_column='fdc_id', max_length=15, null=True)),
                ('registry_id', models.CharField(blank=True, db_column='registry_id', max_length=15, null=True)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.type_country')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.type_county')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.type_state')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.type_battery')),
            ],
            bases=('core.base_domain',),
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('base_equip_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base_equip')),
                ('measurement', models.CharField(blank=True, db_column='measurement', max_length=15)),
                ('battery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.battery')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.type_battery')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.type_pump')),
            ],
            bases=('core.base_equip',),
        ),
        migrations.CreateModel(
            name='Compressor',
            fields=[
                ('base_equip_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base_equip')),
                ('cumulative_m', models.CharField(blank=True, db_column='cumulative_m', max_length=15)),
                ('disc_press_meas', models.BooleanField(blank=True, db_column='disc_press_meas')),
                ('disc_temp_meas', models.BooleanField(blank=True, db_column='disc_temp_meas')),
                ('last_service', models.DateTimeField(blank=True, db_column='last_service')),
                ('rollover', models.DecimalField(blank=True, db_column='rollover', decimal_places=8, max_digits=12)),
                ('rollover_uom', models.CharField(blank=True, db_column='rollover_uom', max_length=15)),
                ('seal_press_meas', models.BooleanField(blank=True, db_column='seal_press_meas')),
                ('stages', models.DecimalField(blank=True, db_column='stages', decimal_places=8, max_digits=12)),
                ('suct_press_meas', models.BooleanField(blank=True, db_column='suct_press_meas')),
                ('suct_temp_meas', models.BooleanField(blank=True, db_column='suct_temp_meas')),
                ('type', models.CharField(blank=True, db_column='type', max_length=15)),
                ('battery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.battery')),
            ],
            bases=('core.base_equip',),
        ),
    ]
