# Generated by Django 3.2.8 on 2021-10-27 02:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain_base',
            fields=[
                ('item_id', models.UUIDField(db_column='item_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_column='active')),
                ('data_status', models.CharField(blank=True, db_column='data_status', max_length=15)),
                ('latitude', models.DecimalField(blank=True, db_column='latitude', decimal_places=8, max_digits=12)),
                ('legacy_id', models.CharField(blank=True, db_column='legacy_id', max_length=15)),
                ('longitude', models.DecimalField(blank=True, db_column='longitude', decimal_places=8, max_digits=12)),
                ('name', models.CharField(db_column='name', max_length=15)),
                ('north', models.BooleanField(blank=True, db_column='north')),
                ('spheroid', models.CharField(blank=True, db_column='spheroid', max_length=15)),
                ('time_zone', models.DecimalField(blank=True, db_column='time_zone', decimal_places=8, max_digits=12)),
                ('x', models.DecimalField(blank=True, db_column='x', decimal_places=8, max_digits=12)),
                ('y', models.DecimalField(blank=True, db_column='y', decimal_places=8, max_digits=12)),
                ('zone1', models.DecimalField(blank=True, db_column='zone', decimal_places=8, max_digits=12)),
            ],
        ),
    ]
