# Generated by Django 3.2.8 on 2021-11-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='name',
            field=models.CharField(db_column='name', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='battery_type',
            name='code',
            field=models.CharField(blank=True, db_column='code', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='battery_type',
            name='code_text',
            field=models.CharField(blank=True, db_column='code_text', max_length=15, unique=True),
        ),
    ]
