# Generated by Django 3.2.8 on 2021-11-05 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base_domain',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='base_domain',
            name='start_datetim',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='base_domain',
            name='end_datetime',
            field=models.DateTimeField(default='01/01/9999 00:00:00'),
        ),
    ]
