# Generated by Django 3.2.8 on 2021-11-12 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_base_domain_last_updt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_domain',
            name='last_updt_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
