# Generated by Django 3.2.8 on 2021-11-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211105_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_domain',
            name='end_datetime',
            field=models.DateTimeField(blank=True, db_column='end_datetime'),
        ),
    ]
