# Generated by Django 3.2.8 on 2021-11-03 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211103_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('domain_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.domain_base')),
                ('name', models.CharField(db_column='name', max_length=15, unique=True)),
                ('contact_name', models.CharField(blank=True, db_column='contact_name', max_length=15, null=True)),
                ('address', models.CharField(blank=True, db_column='address', max_length=15, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=15, null=True)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=15, null=True)),
                ('operator', models.BooleanField(blank=True, db_column='operator', default=True)),
                ('owner', models.BooleanField(blank=True, db_column='owner', default=True)),
                ('purchaser', models.BooleanField(blank=True, db_column='purchaser', default=True)),
                ('transporter', models.BooleanField(blank=True, db_column='transporter', default=True)),
                ('battery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.battery')),
            ],
            bases=('core.domain_base',),
        ),
    ]
