# Generated by Django 3.2.8 on 2021-11-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_base_domain_last_updt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_domain',
            name='start_datetime',
            field=models.DateTimeField(auto_now_add=True, db_column='start_datetime'),
        ),
    ]
