# Generated by Django 3.2.8 on 2021-11-08 22:25

import core.models._base_domain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211109_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_domain',
            name='end_datetime',
            field=models.DateTimeField(db_column='end_datetime', default=core.models._base_domain.end_datetime),
        ),
    ]
