# Generated by Django 3.2.8 on 2021-11-12 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_base_domain_start_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_domain',
            name='last_updt_user',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='base_domain',
            name='update_source',
            field=models.CharField(blank=True, db_column='update_source', editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='base_domain',
            name='version',
            field=models.CharField(blank=True, db_column='version', editable=False, max_length=15),
        ),
    ]
