# Generated by Django 3.2.8 on 2021-11-03 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_company_battery_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='battery_id',
        ),
        migrations.AddField(
            model_name='battery',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
    ]
