# Generated by Django 3.2.8 on 2021-11-09 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_base_domain_end_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('base_domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base_domain')),
                ('accounting_id', models.CharField(blank=True, db_column='accounting_id', max_length=15, null=True)),
                ('serial_id', models.CharField(blank=True, db_column='serial_id', max_length=15, null=True)),
                ('registry_id', models.CharField(blank=True, db_column='registry_id', max_length=15, null=True)),
                ('company_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.field')),
            ],
            bases=('core.base_domain',),
        ),
    ]
