# Generated by Django 3.2.8 on 2021-11-03 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_battery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.battery_type'),
        ),
    ]
