# Generated by Django 3.2.8 on 2021-11-09 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_field_company_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='company_id',
        ),
        migrations.AddField(
            model_name='battery',
            name='field_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.field'),
        ),
    ]
