# Generated by Django 4.0.7 on 2022-10-07 14:52

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='code_list',
            fields=[
                ('LIST_TYPE', models.CharField(db_index=True, max_length=100)),
                ('CULTURE', models.CharField(db_index=True, default='Culture', max_length=10)),
                ('CODE', models.CharField(db_index=True, max_length=100)),
                ('CODE_TEXT', models.CharField(db_index=True, max_length=100, null=True)),
                ('PARENT', models.CharField(db_index=True, max_length=100, null=True)),
                ('LEGACY_CODE', models.CharField(max_length=50, null=True)),
                ('VAL1', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('VAL2', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('VAL3', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('VAL4', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('VAL5', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('VAL6', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('VAL7', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('VAL8', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('VAL9', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('VAL10', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('DATE1', models.DateField(null=True)),
                ('DATE2', models.DateField(null=True)),
                ('DATE3', models.DateField(null=True)),
                ('DATE4', models.DateField(null=True)),
                ('DATE5', models.DateField(null=True)),
                ('CHAR1', models.CharField(max_length=1000, null=True)),
                ('CHAR2', models.CharField(max_length=1000, null=True)),
                ('CHAR3', models.CharField(max_length=1000, null=True)),
                ('CHAR4', models.CharField(max_length=1000, null=True)),
                ('CHAR5', models.CharField(max_length=1000, null=True)),
                ('LAYER_NAME', models.CharField(max_length=50)),
                ('DESCRIPTION_ID', models.CharField(max_length=100, null=True)),
                ('HIDDEN', models.CharField(max_length=5, null=True)),
                ('LAST_UPDT_USER', models.CharField(max_length=100, null=True)),
                ('LAST_UPDT_DATE', models.DateField(default=django.utils.timezone.now, null=True)),
                ('VERSION', models.CharField(default=uuid.uuid4, max_length=32)),
                ('DB_ID', models.CharField(max_length=32, null=True)),
                ('ROW_ID', models.CharField(default=uuid.uuid4, max_length=32, primary_key=True, serialize=False)),
                ('STATUS', models.CharField(max_length=10, null=True)),
                ('REV_GRP_ID', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
