# Generated by Django 4.0.7 on 2022-08-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_list',
            name='LAST_UPDT_DATE',
            field=models.DateField(default='2022-08-16', null=True),
        ),
    ]
