# Generated by Django 4.0.7 on 2022-09-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code_list',
            options={'ordering': ['id']},
        ),
    ]
