# Generated by Django 4.0.8 on 2022-10-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_list', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='code_list',
            index=models.Index(fields=['LIST_TYPE'], name='code_list_c_LIST_TY_53bbd6_idx'),
        ),
    ]
