# Generated by Django 4.0.7 on 2022-08-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_list', '0002_alter_code_list_last_updt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_list',
            name='LAST_UPDT_DATE',
            field=models.DateField(default='2022-08-18', null=True),
        ),
    ]
