# Generated by Django 4.1.8 on 2023-04-18 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resources_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CULTURE', models.CharField(db_index=True, max_length=10)),
                ('ID', models.CharField(max_length=100)),
                ('SHORT_LABEL', models.CharField(max_length=200, null=True)),
                ('MOBILE_LABEL', models.CharField(max_length=200, null=True)),
                ('ICON', models.CharField(max_length=100, null=True)),
                ('PARENT', models.CharField(max_length=500, null=True)),
                ('LAYER_NAME', models.CharField(max_length=50)),
                ('HIDDEN', models.CharField(max_length=5, null=True)),
                ('LAST_UPDT_USER', models.CharField(max_length=100, null=True)),
                ('LAST_UPDT_DATE', models.DateField(default=django.utils.timezone.now, null=True)),
                ('VERSION', models.CharField(default='819145746e1542d99f8c795777c84cac', max_length=32)),
                ('DB_ID', models.CharField(max_length=32, null=True)),
                ('ROW_ID', models.CharField(db_index=True, default='c2197582d6b34ba7a3f84300c2765e63', max_length=32)),
                ('STATUS', models.CharField(max_length=10, null=True)),
                ('SORT_ORDER', models.DecimalField(decimal_places=0, max_digits=18, null=True)),
                ('REV_GRP_ID', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
