# Generated by Django 4.1.8 on 2023-04-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='23e7f9d3abd5404e9e163cdc00c08b83', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='bf96bb9ffac84d32982941b151c0e952', max_length=32, null=True),
        ),
    ]
