# Generated by Django 4.1.8 on 2023-04-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_roles_property_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='PROPERTY_ID',
        ),
    ]
