# Generated by Django 4.1.8 on 2023-04-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_property', '0005_remove_roles_property_roles_id'),
        ('roles', '0003_remove_roles_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='PROPERTY_ID',
            field=models.ManyToManyField(related_name='roles', to='roles_property.roles_property'),
        ),
    ]
