version: "3.8"
services:
  frontend:
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: ./all_dockerfiles/local/frontend/Dockerfile
    container_name: ligeiaai-frontend-1
    env_file:
      - .env
    volumes:
      - ../../frontend:/frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - net
  client:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - net
  django:
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: ./all_dockerfiles/local/django/Dockerfile
    command: /start
    container_name: ligeiaai-django-1
    env_file:
      - .env
    volumes:
      - ../../:/django
    environment:
      - CELERY_BROKER=redis://redis:6379/1
      - CELERY_BACKEND=redis://redis:6379/1
    ports:
      - "8000:8000"
    networks:
      - net
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "cluster.name=my-cluster"
      - "node.name=node-1"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - net
networks:
  net:
    driver: bridge