# Generated by Django 2.2.12 on 2022-02-22 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Опишите заключение по ТО', max_length=1000, verbose_name='Заключение')),
                ('createdDate', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания')),
                ('updatedDate', models.DateTimeField(auto_now=True, help_text='Дата и время создания')),
                ('maintenanceType', models.CharField(choices=[('maintenance1', 'TO1'), ('maintenance2', 'TO2'), ('maintenance3', 'TO3')], help_text='Укажите ТО, которое было проделано', max_length=100, verbose_name='Вид ТО')),
                ('maintenanceDateStart', models.DateTimeField(help_text='Укажите начало работы ТО', verbose_name='Начало')),
                ('maintenanceDateEnd', models.DateTimeField(help_text='Укажите конец работы ТО', verbose_name='Конец')),
            ],
        ),
        migrations.CreateModel(
            name='Max_prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Опишите заключение проделанного ремонта', max_length=1000, verbose_name='Заключение')),
                ('createdDate', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания')),
                ('updatedDate', models.DateTimeField(auto_now=True, help_text='Дата и время создания')),
                ('repairType', models.CharField(choices=[('repair1', 'АВР'), ('repair2', 'ТР')], help_text='Укажите вид ремонт,который был проделан', max_length=100, verbose_name='Вид ТО')),
                ('repairDateStart', models.DateTimeField(help_text='Укажите дату и время начала ремонта', verbose_name='Начало')),
                ('repairDateEnd', models.DateTimeField(help_text='Укажите дату и время конца ремонта', verbose_name='Конец')),
                ('failure', models.BooleanField(default=False, verbose_name='Ремонт связанный с отказом оборудования')),
                ('pump', models.ForeignKey(help_text='Укажите насос, на которой был проделан ремонт', on_delete=django.db.models.deletion.PROTECT, to='main.Pump', verbose_name='Насос')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('place', models.CharField(max_length=100, null=True)),
                ('ip', models.CharField(max_length=100, null=True)),
                ('ip_id', models.IntegerField(null=True)),
                ('ip_channel', models.IntegerField(null=True)),
                ('register_modbus', models.IntegerField(null=True)),
                ('unit', models.CharField(max_length=100, null=True)),
                ('max_v', models.FloatField(null=True)),
                ('min_v', models.FloatField(null=True)),
                ('pump', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Pump')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Код станции', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v', models.FloatField(null=True)),
                ('q', models.BooleanField(default=True)),
                ('t', models.DateTimeField()),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='RepairWorkTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workPerformed', models.CharField(choices=[('bearing', 'Замена подшипника (двухрядного шарикового; роликового)'), ('wheel', 'Замена рабочего колеса'), ('shaft', 'Замена вала'), ('rotor', 'Замена ротора')], help_text='Укажите ремонт, которая была выполнена', max_length=100, verbose_name='Выберите выполненную работу')),
                ('bearingElement', models.CharField(choices=[('element1', 'Подшипниковый узел насоса'), ('element2', 'Электродвигатель')], help_text='Укажите элемент подшипник, который был заменен', max_length=100, null=True, verbose_name='Элемент подшипника')),
                ('bearingType', models.CharField(choices=[('type1', 'Шариковый'), ('type2', 'Роликовый')], help_text='Укажите тип подшипника, который был заменен', max_length=100, null=True, verbose_name='Тип подшипника')),
                ('bearingModel', models.CharField(choices=[('model1', 'NUP 313ECJ'), ('model2', 'NUP 317ECJ'), ('model3', '7314 BECBM'), ('model4', '7318 BECBM'), ('model5', '6322С3'), ('model6', '6316С3')], help_text='Укажите модель подшипника, который был заменен', max_length=100, null=True, verbose_name='Модель подшипника')),
                ('wheelModel', models.CharField(choices=[('model1', '400,00 мм'), ('model2', '565,00 мм')], help_text='Укажите работы, которое было заменено', max_length=100, null=True, verbose_name='Модель колеса')),
                ('shaftModel', models.CharField(choices=[('model1', 'D60'), ('model2', 'D75')], help_text='Укажите модель вала, который был заменен', max_length=100, null=True, verbose_name='Модель вала')),
                ('datePerformed', models.DateTimeField(help_text='Укажите дату и время работы, которая была выполнена', verbose_name='Выберите дату и время работы')),
                ('mttf', models.IntegerField()),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Repair')),
            ],
        ),
        migrations.AddField(
            model_name='repair',
            name='station',
            field=models.ForeignKey(help_text='Укажите станцию, на которой был проделан ремонт', on_delete=django.db.models.deletion.PROTECT, to='main.Station', verbose_name='Станция'),
        ),
        migrations.AddField(
            model_name='pump',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Station'),
        ),
        migrations.CreateModel(
            name='MaintenanceWorkTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workPerformed', models.CharField(choices=[('oil', 'Замена смазки в подшипниках насоса'), ('sealant', 'Замена уплотнения')], help_text='Укажите работы, которая была выполнена', max_length=100, verbose_name='Выберите выполненную работу')),
                ('oil', models.CharField(choices=[('oil0', '-'), ('oil1', 'Bechem Berutox FE 18 EP')], help_text='Выберите из списка смазку, которая была использована во время ТО', max_length=100, null=True, verbose_name='Смазка')),
                ('sealant', models.CharField(choices=[('sealant1', 'LP-D-S32-D20/60-DE1'), ('sealant2', 'Джон Крэйн Мех. уплотн., двойное, открытое'), ('sealant3', 'FE08, Burgmann, LP-D-S32-D20<')], help_text='Выберите из списка уплотнение, которое было заменено', max_length=100, null=True, verbose_name='Уплотнение')),
                ('datePerformed', models.DateTimeField(help_text='Укажите дату и время работы, которая была выполнена', verbose_name='Выберите дату и время выполненной работы')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Maintenance')),
            ],
        ),
        migrations.AddField(
            model_name='maintenance',
            name='pump',
            field=models.ForeignKey(help_text='Укажите насос, на которой было проделано ТО', on_delete=django.db.models.deletion.PROTECT, to='main.Pump', verbose_name='Насос'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='station',
            field=models.ForeignKey(help_text='Укажите станцию, на которой было проделано ТО', on_delete=django.db.models.deletion.PROTECT, to='main.Station', verbose_name='Станция'),
        ),
    ]
