# Generated by Django 2.2.12 on 2022-02-27 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220227_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediction',
            name='prediction',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='status',
        ),
    ]
