# Generated by Django 4.1.8 on 2023-04-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='layer_name',
        ),
    ]
