# Generated by Django 3.2.10 on 2021-12-18 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dummy',
        ),
    ]
