# Generated by Django 4.1.3 on 2022-11-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='2af4af918dcf45a1b4edcf1a14ca9c08', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='f2e1b556e4ef4b07a66699705f65567a', max_length=32),
        ),
    ]
