# Generated by Django 4.1.3 on 2022-11-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0002_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='6cc99a0b3fcb4ab4934690748e974008', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='5b70a985585b4d808ddb309c13b6b203', max_length=32),
        ),
    ]
