# Generated by Django 4.1.3 on 2022-11-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0002_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='4e74a8c5c0b2463cae17ff729a0d4844', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='be69eae329f345f8a7bdb25994d07a10', max_length=32),
        ),
    ]
