# Generated by Django 4.1.3 on 2022-11-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0003_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='36b7c88b868b42cfb1653c2dfe51bc58', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='29240fb8a9da4583addb3115f2566cf6', max_length=32),
        ),
    ]
