# Generated by Django 4.1.3 on 2022-11-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0003_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='0e83e05de3324b009887be7d8bcd6f04', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='a4b39d9acaf14160b806fe116a894a58', max_length=32),
        ),
    ]
