# Generated by Django 4.1.3 on 2022-11-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0004_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='9b5ed2d832da4859889878a9aec4dc28', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='05436ec9f53b4fa3a855ef9776369318', max_length=32),
        ),
    ]
