# Generated by Django 4.1.3 on 2022-11-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0004_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='a06b283710c1433daa43bb8db7a0c127', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='c274ace0a2de4bf394215316348666e2', max_length=32),
        ),
    ]
