# Generated by Django 4.1.3 on 2022-11-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0005_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='cb95bb3449a44fc8827b210a44856227', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='e9e3076f933b43aa8d161cdd1a6be36e', max_length=32),
        ),
    ]
