# Generated by Django 4.1.3 on 2022-11-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0006_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='962be98a97794a56976593157f4fbf13', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='75be82966ecb46dc991bd888b469a45a', max_length=32),
        ),
    ]
