# Generated by Django 4.1.3 on 2022-11-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0007_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='b058a283539649d782f31fe148e16979', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='fdfe81c38cf240998d42dc17b213358b', max_length=32),
        ),
    ]
