# Generated by Django 4.1.3 on 2022-11-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0008_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='716ff4bc63174c2d865eb4ddea96ed78', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='cd40abb53c6d454794c3f0c17f963b8c', max_length=32),
        ),
    ]
