# Generated by Django 4.1.3 on 2022-11-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0009_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='c1f0a99235614897b057a56a090a5c77', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='22403e3a271d41c6bd111b0e11001f3b', max_length=32),
        ),
    ]
