# Generated by Django 4.1.3 on 2022-11-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0010_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='f391b567e434450992c51c6e9d666fef', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='32ff2fb4e13a477ab51cae4aad411edd', max_length=32),
        ),
    ]
