# Generated by Django 4.1.3 on 2022-11-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0011_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='ad53d515e5ed4910aeadff943f404f34', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='80c9c35386694462982aabf8835f2946', max_length=32),
        ),
    ]
