# Generated by Django 4.1.3 on 2022-11-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0012_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='976fa8717fb2409eb063fe993f89e4f6', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='c7ca2ea3737b4c01993e9921c9cb7356', max_length=32),
        ),
    ]
