# Generated by Django 4.1.3 on 2022-11-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0013_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='e0aec4b746d243d9ae867932ca745980', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='4fd75ab6c66b42868edb8ff69d801872', max_length=32),
        ),
    ]
