# Generated by Django 4.1.3 on 2022-11-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0015_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='d111224fc7804b8cbfc8893602259bf7', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='e60b2fbdbe514aacaa2f1392fb997968', max_length=32),
        ),
    ]
