# Generated by Django 4.1.3 on 2022-11-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0016_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='30075b7039894573acbed27ef1258723', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='c7639a5b265a41aab76bcef3bbe9c458', max_length=32),
        ),
    ]
