# Generated by Django 4.1.3 on 2022-11-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0017_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='9c90a3dc97ad47c1b65c555546cb0a55', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='6d1e56c96b3843a982eba10d7813fa59', max_length=32),
        ),
    ]
