# Generated by Django 4.1.3 on 2022-11-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0018_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='ddc07526ee34487580b475f6dfa1306d', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='ec1fa39f7efc48a0ba8aea32e75d6040', max_length=32),
        ),
    ]
