# Generated by Django 4.1.3 on 2022-12-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0019_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='0fef4b97780849ed9955b8537100eeaa', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='e3e8b2ddc55d4f0b87ee63f179407598', max_length=32),
        ),
    ]
