# Generated by Django 4.1.3 on 2022-11-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0019_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='28cbf78a4cf64ec4aae09b8b847a4a66', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='50adcce5e5514db18293764a4a2fd5c3', max_length=32),
        ),
    ]
