# Generated by Django 4.1.3 on 2022-11-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0020_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='671473f0e793486f9c3ef1696d44421b', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='d6f04adc76084cce81b7649cacb5b4fa', max_length=32),
        ),
    ]
