# Generated by Django 4.1.3 on 2022-12-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0021_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='4c7997e95a44424d97cb9b5dd29d16cd', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='22b21509829b4034b1b35e5109825c8f', max_length=32),
        ),
    ]
