# Generated by Django 4.1.3 on 2022-11-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0021_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='4de7c4e499fd4815b3015d6a03117ba9', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='e2a5a43fed3844638101f57f873143ca', max_length=32),
        ),
    ]
