# Generated by Django 4.1.3 on 2022-11-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0022_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='e35bde8f89c44449a2fba1d81097b564', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='5605aa4a49da4bdfaa20977882735857', max_length=32),
        ),
    ]
