# Generated by Django 4.1.3 on 2022-12-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0022_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='d624c985ba5b4e04b33f6523ff539089', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='0e06b8c1a0a74e06913ab114ff8107eb', max_length=32),
        ),
    ]
