# Generated by Django 4.1.3 on 2022-12-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0023_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='7bad02832d42459bb47f90f26d4b9f30', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='772937aa66374361bf2a4a74ac499fdb', max_length=32),
        ),
    ]
