# Generated by Django 4.1.3 on 2022-11-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0023_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='0e2f21ed70264f4091772c8dab57bb79', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='dd231ee15f5449ccaed6bedfdddbf91e', max_length=32),
        ),
    ]
