# Generated by Django 4.1.3 on 2022-11-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0024_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='5944ca5eab2045acbdd1d2c7d53a1910', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='ccdb530a9799424884698e2cfaf1bb17', max_length=32),
        ),
    ]
