# Generated by Django 4.1.4 on 2022-12-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0024_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='b249e8d7051a4346b7e30c60c02b48b7', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='1946a349ddc24a72b8678df62382f22c', max_length=32),
        ),
    ]
