# Generated by Django 4.1.3 on 2022-11-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0026_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='f85be22b38264c9b845183da11022b67', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='95f8c6f8839046f3b7cfc9d14ad3a1df', max_length=32),
        ),
    ]
