# Generated by Django 4.1.3 on 2022-11-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0027_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='6a86d6886fef4dc8bfa5cff05fe3f46a', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='98d565fb2b3c4fcd93546dad6d657def', max_length=32),
        ),
    ]
