# Generated by Django 4.1.3 on 2022-11-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0028_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='b8e21e28f38a4065a52e974bf548d3a7', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='68feb6c9a6c54292843ded474d3729cf', max_length=32),
        ),
    ]
