# Generated by Django 4.1.3 on 2022-11-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0029_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='f6cfae7bc3e24ff38c721e6e2197231d', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='c737704c576947a5b896e3405b3580a9', max_length=32),
        ),
    ]
