# Generated by Django 4.1.3 on 2022-11-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0030_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='8125a1888d234b87ad65846a5ba9a758', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='c4dc9afc4c7543459073f2f2db4b3450', max_length=32),
        ),
    ]
