# Generated by Django 4.1.3 on 2022-11-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0031_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='9f25063eee8544eaa09f2ee55bc2f18b', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='098d6ada472b470895c54119c7b75a76', max_length=32),
        ),
    ]
