# Generated by Django 4.1.3 on 2022-11-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0032_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='6323a23f406b44c2b11d16028f7de9c3', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='cc3fcf9d556c4068bacbcd591dc3f60b', max_length=32),
        ),
    ]
