# Generated by Django 4.1.3 on 2022-11-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0033_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='104a14894bf944049abc951000c531a6', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='ec4743300fd249f6a5741a01d4fb45ea', max_length=32),
        ),
    ]
