# Generated by Django 4.1.3 on 2022-11-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0034_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='3a3a032c64694bc1aa54c7e7a5464ab5', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='f0c3fbff0e604bb7bf11cb1dc906e579', max_length=32),
        ),
    ]
