# Generated by Django 4.1.3 on 2022-11-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0035_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='e204c9294c3e46f5a1ee648ce527cd90', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='c7c4908d0c054b44873b33b8dd8f5a1c', max_length=32),
        ),
    ]
