# Generated by Django 4.1.3 on 2022-11-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0036_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='7b8e3d7742d54a31b9da5701bc81b702', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='f5a795a38b9d4d09970edd309fcbfc25', max_length=32),
        ),
    ]
