# Generated by Django 4.1.3 on 2022-11-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0037_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='e670192729b546ddb33cbb06495332e3', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='17fef4fd9b8e456db76e194ce8559dac', max_length=32),
        ),
    ]
