# Generated by Django 4.1.3 on 2022-11-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0038_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='7cb0bc8105394035abe1c5c0c1361af2', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='6bb25576e0ab46bb86a5c57e404e0975', max_length=32),
        ),
    ]
