# Generated by Django 4.1.3 on 2022-11-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0039_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='ca7d69d49b114b0d95bb2e12a360f2ec', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='02425d6458ef4eaa83f398785f19438e', max_length=32),
        ),
    ]
