# Generated by Django 4.1.3 on 2022-11-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_list', '0040_alter_resource_list_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_list',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='370a0e83ff9440259a11355c949449e3', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource_list',
            name='VERSION',
            field=models.CharField(default='4937d146bcb347dfa062e22d901ffe01', max_length=32),
        ),
    ]
