export const columns = [
    {
        field: "LIST_TYPE",
        headerName: "List type",
        width: 200,
        editable: true,
    },
    {
        field: "CULTURE",
        headerName: "Culture",
        width: 100,
        editable: true,
    },
    {
        field: "CODE",
        headerName: "Code",
        width: 100,
        editable: true,
    },
    {
        field: "CODE_TEXT",
        headerName: "Code Text",
        width: 100,
        editable: true,
    },

    {
        field: "PARENT",
        headerName: "Parent",
        width: 100,
        editable: true,
    },

    {
        field: "LEGACY_CODE",
        headerName: "Legacy Code",
        width: 100,
        editable: true,
    },
    {
        field: "VAL1",
        headerName: "Val1",
        width: 100,
        editable: true,
        type: "number",
    },
    {
        field: "VAL2",
        headerName: "Val2",
        width: 100,
        editable: true,
        type: "number",
    },
    {
        field: "VAL3",
        headerName: "Val3",
        width: 100,
        editable: true,
        type: "number",
    },
    {
        field: "VAL4",
        headerName: "Val4",
        width: 100,
        editable: true,
        type: "number",
    },
    {
        field: "VAL5",
        headerName: "Val5",
        width: 100,
        editable: true,
        type: "number",
    },
    {
        field: "VAL6",
        headerName: "Val6",
        width: 100,
        editable: true,
        type: "number",
    },
    {
        field: "VAL7",
        headerName: "Val7",
        width: 100,
        editable: true,
        type: "number",
    },
    {
        field: "VAL8",
        headerName: "Val8",
        width: 100,
        editable: true,
        type: "number",
    },
    {
        field: "VAL9",
        headerName: "Val9",
        width: 100,
        editable: true,
        type: "number",
    },
    {
        field: "VAL10",
        headerName: "Val10",
        width: 100,
        editable: true,
        type: "number",
    },

    {
        field: "DATE1",
        headerName: "Date1",
        width: 100,
        editable: true,
        type: "date",
    },
    {
        field: "DATE2",
        headerName: "Date2",
        width: 100,
        editable: true,
        type: "date",
    },
    {
        field: "DATE3",
        headerName: "Date3",
        width: 100,
        editable: true,
        type: "date",
    },
    {
        field: "DATE4",
        headerName: "Date4",
        width: 100,
        editable: true,
        type: "date",
    },
    {
        field: "DATE5",
        headerName: "Date5",
        width: 100,
        editable: true,
        type: "date",
    },

    {
        field: "CHAR1",
        headerName: "Char1",
        width: 100,
        editable: true,
    },
    {
        field: "CHAR2",
        headerName: "Char2",
        width: 100,
        editable: true,
    },
    {
        field: "CHAR3",
        headerName: "Char3",
        width: 100,
        editable: true,
    },
    {
        field: "CHAR4",
        headerName: "Char4",
        width: 100,
        editable: true,
    },
    {
        field: "CHAR5",
        headerName: "Char5",
        width: 100,
        editable: true,
    },

    {
        field: "LAYER_NAME",
        headerName: "Layer Name",
        width: 100,
        editable: true,
    },
    {
        field: "DESCRIPTION_ID",
        headerName: "Description Id",
        width: 100,
        editable: true,
    },
    {
        field: "HIDDEN",
        headerName: "Hidden",
        width: 100,
        editable: true,
    },
    {
        field: "LAST_UPDT_USER",
        headerName: "Last Update User",
        width: 100,
        editable: false,
    },
    {
        field: "LAST_UPDT_DATE",
        headerName: "Last Update Date",
        width: 100,
        editable: false,
    },
];