# Generated by Django 4.1.8 on 2023-04-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_layer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='CREATE_SOURCE',
            field=models.CharField(default='x', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='END_DATETIME',
            field=models.DateField(db_index=True, default='9000-01-01'),
        ),
        migrations.AlterField(
            model_name='item',
            name='LAST_UPDT_DATE',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='LAYER_NAME',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ROW_ID',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='item',
            name='UPDATE_SOURCE',
            field=models.CharField(default='x', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='VERSION',
            field=models.CharField(max_length=32),
        ),
    ]
