from django.db import models

class code_list (models.Model): 
    LIST_TYPE = models.CharField(primary_key = False, null = False, max_length = 100)
    CULTURE = models.CharField(primary_key = False, null = False, default = "Culture", max_length = 10)
    CODE = models.CharField(primary_key = False, null = False, max_length = 100)
    CODE_TEXT = models.CharField(primary_key = False, null = True, max_length = 100)
    PARENT = models.CharField(primary_key = False, null = True, max_length = 100)
    LEGACY_CODE = models.CharField(primary_key = False, null = True, max_length = 50)
    VAL1 = models.DecimalField(decimal_places = 12, primary_key = False, null = True, max_digits = 28)
    VAL2 = models.DecimalField(decimal_places = 12, primary_key = False, null = True, max_digits = 28)
    VAL3 = models.DecimalField(decimal_places = 12, primary_key = False, null = True, max_digits = 28)
    VAL4 = models.DecimalField(decimal_places = 12, primary_key = False, null = True, max_digits = 28)
    VAL5 = models.DecimalField(decimal_places = 12, primary_key = False, null = True, max_digits = 28)
    VAL6 = models.DecimalField(decimal_places = 12, primary_key = False, null = True, max_digits = 28)
    VAL7 = models.DecimalField(decimal_places = 12, primary_key = False, null = True, max_digits = 28)
    VAL8 = models.DecimalField(decimal_places = 12, primary_key = False, null = True, max_digits = 28)
    VAL9 = models.DecimalField(decimal_places = 12, primary_key = False, null = True, max_digits = 28)
    VAL10 = models.DecimalField(decimal_places = 12, primary_key = False, null = True, max_digits = 28)
    DATE1 = models.DateField(primary_key = False, null = True)
    DATE2 = models.DateField(primary_key = False, null = True)
    DATE3 = models.DateField(primary_key = False, null = True)
    DATE4 = models.DateField(primary_key = False, null = True)
    DATE5 = models.DateField(primary_key = False, null = True)
    CHAR1 = models.CharField(primary_key = False, null = True, max_length = 1000)
    CHAR2 = models.CharField(primary_key = False, null = True, max_length = 1000)
    CHAR3 = models.CharField(primary_key = False, null = True, max_length = 1000)
    CHAR4 = models.CharField(primary_key = False, null = True, max_length = 1000)
    CHAR5 = models.CharField(primary_key = False, null = True, max_length = 1000)
    LAYER_NAME = models.CharField(primary_key = False, null = False, max_length = 50)
    DESCRIPTION_ID = models.CharField(primary_key = False, null = True, max_length = 100)
    HIDDEN = models.CharField(primary_key = False, null = True, max_length = 5)
    LAST_UPDT_USER = models.CharField(primary_key = False, null = True, max_length = 100)
    LAST_UPDT_DATE = models.DateField(primary_key = False, null = True, default = "Now")
    VERSION = models.CharField(primary_key = False, null = False, default = "Guid", max_length = 32)
    DB_ID = models.CharField(primary_key = False, null = True, max_length = 32)
    ROW_ID = models.CharField(primary_key = False, null = False, default = "Guid", max_length = 32)
    STATUS = models.CharField(primary_key = False, null = True, max_length = 10)
    REV_GRP_ID = models.CharField(primary_key = False, null = True, max_length = 32)
    