from django.db import models

class item_property (models.Model): 
    ITEM_ID = models.CharField(primary_key = False, null = False, max_length = 32)
    ITEM_TYPE = models.CharField(primary_key = False, null = False, max_length = 14)
    START_DATETIME = models.DateField(primary_key = False, null = False)
    END_DATETIME = models.DateField(primary_key = False, null = False, default = "EndDatetime")
    PROPERTY_TYPE = models.CharField(primary_key = False, null = False, max_length = 15)
    PROPERTY_VALUE = models.DecimalField(decimal_places = 12, primary_key = False, null = True, max_digits = 28)
    PROPERTY_DATE = models.DateField(primary_key = False, null = True)
    PROPERTY_STRING = models.CharField(primary_key = False, null = True, max_length = 200)
    LAST_UPDT_USER = models.CharField(primary_key = False, null = True, max_length = 100)
    LAST_UPDT_DATE = models.DateField(primary_key = False, null = True, default = "Now")
    VERSION = models.CharField(primary_key = False, null = False, default = "Guid", max_length = 32)
    DB_ID = models.CharField(primary_key = False, null = True, max_length = 32)
    ROW_ID = models.CharField(primary_key = False, null = False, default = "Guid", max_length = 32)
    STATUS = models.CharField(primary_key = False, null = True, max_length = 10)
    REV_GRP_ID = models.CharField(primary_key = False, null = True, max_length = 32)
    UPDATE_SOURCE = models.CharField(primary_key = False, null = True, default = "SourceType", max_length = 1)
    CREATE_SOURCE = models.CharField(primary_key = False, null = True, default = "SourceType", max_length = 1)
