from django.db import models

class CODE_LIST (models.Model): 
  LIST_TYPE = models.CharField(max_length = 100, IsIdentity = False, null = False, default = None, pkorder = None)
  CULTURE = models.CharField(max_length = 10, IsIdentity = False, null = False, default = Culture, pkorder = None)
  CODE = models.CharField(max_length = 100, IsIdentity = False, null = False, default = None, pkorder = None)
  CODE_TEXT = models.CharField(max_length = 100, IsIdentity = False, null = True, default = None, pkorder = None)
  PARENT = models.CharField(max_length = 100, IsIdentity = False, null = True, default = None, pkorder = None)
  LEGACY_CODE = models.CharField(max_length = 50, IsIdentity = False, null = True, default = None, pkorder = None)
  VAL1 = models.IntegerField(max_length = 28, IsIdentity = False, null = True, default = None, pkorder = None)
  VAL2 = models.IntegerField(max_length = 28, IsIdentity = False, null = True, default = None, pkorder = None)
  VAL3 = models.IntegerField(max_length = 28, IsIdentity = False, null = True, default = None, pkorder = None)
  VAL4 = models.IntegerField(max_length = 28, IsIdentity = False, null = True, default = None, pkorder = None)
  VAL5 = models.IntegerField(max_length = 28, IsIdentity = False, null = True, default = None, pkorder = None)
  VAL6 = models.IntegerField(max_length = 28, IsIdentity = False, null = True, default = None, pkorder = None)
  VAL7 = models.IntegerField(max_length = 28, IsIdentity = False, null = True, default = None, pkorder = None)
  VAL8 = models.IntegerField(max_length = 28, IsIdentity = False, null = True, default = None, pkorder = None)
  VAL9 = models.IntegerField(max_length = 28, IsIdentity = False, null = True, default = None, pkorder = None)
  VAL10 = models.IntegerField(max_length = 28, IsIdentity = False, null = True, default = None, pkorder = None)
  DATE1 = models.DateField(max_length = None, IsIdentity = False, null = True, default = None, pkorder = None)
  DATE2 = models.DateField(max_length = None, IsIdentity = False, null = True, default = None, pkorder = None)
  DATE3 = models.DateField(max_length = None, IsIdentity = False, null = True, default = None, pkorder = None)
  DATE4 = models.DateField(max_length = None, IsIdentity = False, null = True, default = None, pkorder = None)
  DATE5 = models.DateField(max_length = None, IsIdentity = False, null = True, default = None, pkorder = None)
  CHAR1 = models.CharField(max_length = 1000, IsIdentity = False, null = True, default = None, pkorder = None)
  CHAR2 = models.CharField(max_length = 1000, IsIdentity = False, null = True, default = None, pkorder = None)
  CHAR3 = models.CharField(max_length = 1000, IsIdentity = False, null = True, default = None, pkorder = None)
  CHAR4 = models.CharField(max_length = 1000, IsIdentity = False, null = True, default = None, pkorder = None)
  CHAR5 = models.CharField(max_length = 1000, IsIdentity = False, null = True, default = None, pkorder = None)
  LAYER_NAME = models.CharField(max_length = 50, IsIdentity = False, null = False, default = None, pkorder = None)
  DESCRIPTION_ID = models.CharField(max_length = 100, IsIdentity = False, null = True, default = None, pkorder = None)
  HIDDEN = models.CharField(max_length = 5, IsIdentity = False, null = True, default = None, pkorder = None)
  LAST_UPDT_USER = models.CharField(max_length = 100, IsIdentity = False, null = True, default = None, pkorder = None)
  LAST_UPDT_DATE = models.DateField(max_length = None, IsIdentity = False, null = True, default = Now, pkorder = None)
  VERSION = models.CharField(max_length = 32, IsIdentity = False, null = False, default = Guid, pkorder = None)
  DB_ID = models.CharField(max_length = 32, IsIdentity = False, null = True, default = None, pkorder = None)
  ROW_ID = models.CharField(max_length = 32, IsIdentity = False, null = False, default = Guid, pkorder = 1)
  STATUS = models.CharField(max_length = 10, IsIdentity = False, null = True, default = None, pkorder = None)
  REV_GRP_ID = models.CharField(max_length = 32, IsIdentity = False, null = True, default = None, pkorder = None)
  