from django.db import models

class type_property (models.Model): 
    TYPE = models.CharField(null = False, max_length = 14)
    PROPERTY_NAME = models.CharField(null = False, max_length = 15)
    PROP_GRP = models.CharField(null = True, max_length = 50)
    PROP_GRP_PRNT = models.CharField(null = True, max_length = 50)
    LABEL_ID = models.CharField(null = True, max_length = 100)
    TABLE_NAME = models.CharField(null = True, max_length = 50)
    COLUMN_NAME = models.CharField(null = True, max_length = 50)
    PROPERTY_TYPE = models.CharField(null = True, max_length = 100)
    PROPERTY_CLASS = models.CharField(null = True, max_length = 100)
    UNICODE = models.CharField(null = True, max_length = 5)
    CODE_LIST = models.CharField(null = True, max_length = 100)
    CODE_LIST_FLTR = models.CharField(null = True, max_length = 100)
    CODE_LIST_LVL = models.DecimalField(decimal_places = 0, null = True, max_digits = 18)
    PARENT_CL_PROP = models.CharField(null = True, max_length = 15)
    VALUE_FILTER = models.CharField(null = True, max_length = 100)
    UI_EDIT_CLASS = models.CharField(null = True, max_length = 100)
    SORT_ORDER = models.DecimalField(decimal_places = 0, null = True, max_digits = 18)
    MANDATORY = models.CharField(null = True, max_length = 5)
    HIDDEN = models.CharField(null = True, max_length = 5)
    IS_KEY = models.CharField(null = True, max_length = 5)
    LENGTH = models.DecimalField(decimal_places = 12, null = True, max_digits = 28)
    DECIMALS = models.DecimalField(decimal_places = 12, null = True, max_digits = 28)
    UOM = models.CharField(null = True, max_length = 50)
    CHANGE_INTERVAL = models.CharField(null = True, default = "ChangeInterval", max_length = 10)
    DEFAULT_VALUE = models.CharField(null = True, max_length = 50)
    LAYER_NAME = models.CharField(null = False, max_length = 50)
    DESCRIPTION_ID = models.CharField(null = True, max_length = 100)
    LAST_UPDT_USER = models.CharField(null = True, max_length = 100)
    LAST_UPDT_DATE = models.DateField(null = True, default = "2022-07-26")
    VERSION = models.CharField(null = False, default = "cae7ec6f272349feaf9ea89d01e43d9f", max_length = 32)
    DB_ID = models.CharField(null = True, max_length = 32)
    ROW_ID = models.CharField(null = False, default = "821a2ce24f974616a49c6968b33730ad", max_length = 32)
    STATUS = models.CharField(null = True, max_length = 10)
    REV_GRP_ID = models.CharField(null = True, max_length = 32)
    PROP_UNIQUE = models.CharField(null = True, max_length = 20)
    ALLOW_MULTI_EDIT = models.CharField(null = True, max_length = 5)
    DEF_ACCUM_FUNC = models.CharField(null = True, max_length = 20)
    