from django.db import models

class type_link (models.Model): 
    TYPE = models.CharField(null = False, primary_key = 1, max_length = 14)
    FROM_TYPE = models.CharField(null = False, primary_key = 2, max_length = 14)
    FROM_TYPE_CLASS = models.CharField(null = False, primary_key = 3, max_length = 50)
    FROM_CARDINALITY = models.CharField(null = True, max_length = 10)
    TO_TYPE = models.CharField(null = False, primary_key = 4, max_length = 14)
    TO_TYPE_CLASS = models.CharField(null = False, primary_key = 5, max_length = 50)
    TO_CARDINALITY = models.CharField(null = True, max_length = 10)
    COLL_TYPE = models.CharField(null = True, max_length = 14)
    COLL_TYPE_CLASS = models.CharField(null = True, max_length = 50)
    SYSTEM = models.CharField(null = True, max_length = 5)
    MANDATORY = models.CharField(null = True, max_length = 5)
    RELATION_EDIT_CLASS = models.CharField(null = True, max_length = 100)
    LAYER_NAME = models.CharField(null = False, max_length = 50)
    DESCRIPTION_ID = models.CharField(null = True, max_length = 100)
    HIDDEN = models.CharField(null = True, max_length = 5)
    LAST_UPDT_USER = models.CharField(null = True, max_length = 100)
    LAST_UPDT_DATE = models.DateField(null = True, default = "Now")
    VERSION = models.CharField(null = False, default = "Guid", max_length = 32)
    DB_ID = models.CharField(null = True, max_length = 32)
    ROW_ID = models.CharField(null = False, default = "Guid", max_length = 32)
    STATUS = models.CharField(null = True, max_length = 10)
    REV_GRP_ID = models.CharField(null = True, max_length = 32)
    