#!/bin/bash

set -o errexit
set -o nounset

cd backend

worker_ready(){
    celery -A core inspect ping
}

until worker_ready; do 
    >&2 echo 'Celery workers not available :-('
    sleep 1
done
>&2 echo 'Celery workers are available and ready!...:-)'

celery --app core --broker=redis://redis:6379/0 flower
# celery --app core --broker=redis://guest:guest@localhost:6379/0 flower