# Generated by Django 4.0.7 on 2022-08-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_list',
            name='LAST_UPDT_DATE',
            field=models.DateField(default='2022-08-12', null=True),
        ),
    ]
