# Generated by Django 4.1.4 on 2023-01-02 18:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(db_index=True, max_length=50)),
                ('QUALITY_TYPE', models.CharField(max_length=1000)),
                ('CATALOG_NAME', models.CharField(max_length=50)),
                ('CATALOG_SYMBOL', models.CharField(max_length=50)),
                ('RP66_SYMBOL', models.CharField(max_length=10, null=True)),
                ('BASE_UNIT', models.CharField(max_length=10, null=True)),
                ('LAST_UPDT_USER', models.CharField(max_length=100, null=True)),
                ('LAST_UPDT_DATE', models.DateField(default='2023-01-02', null=True)),
                ('VERSION', models.CharField(default=uuid.uuid4, max_length=32)),
                ('DB_ID', models.CharField(max_length=32, null=True)),
                ('ROW_ID', models.CharField(db_index=True, default=uuid.uuid4, max_length=32)),
                ('STATUS', models.CharField(max_length=10, null=True)),
                ('REV_GRP_ID', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
