# Generated by Django 4.1.5 on 2023-01-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0002_alter_uom_last_updt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='BASE_UNIT',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='uom',
            name='CATALOG_NAME',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='uom',
            name='CATALOG_SYMBOL',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='uom',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='aa28186fc02e445ca4c4052ef87f7cbb', max_length=32),
        ),
        migrations.AlterField(
            model_name='uom',
            name='RP66_SYMBOL',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='d3ab989695424358ae6be8a41bacf312', max_length=32),
        ),
    ]
