# Generated by Django 4.1.5 on 2023-01-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0003_alter_uom_base_unit_alter_uom_catalog_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='36726154bf1441bcadf8b4002046ae4f', max_length=32),
        ),
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='9c5ac4254f5e473591b29af35233b428', max_length=32),
        ),
    ]
