# Generated by Django 4.1.5 on 2023-01-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0004_alter_uom_row_id_alter_uom_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='c9f8a363038b40d9aaf8a3228e75dada', max_length=32),
        ),
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='2a16ece120734dd390fbe32cb7c400be', max_length=32),
        ),
    ]
