# Generated by Django 4.1.5 on 2023-01-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0005_alter_uom_row_id_alter_uom_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='32c0526b31dc4855a669fed93d1e2fa4', max_length=32),
        ),
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='c4636f12a9094208b6b225bd14642b22', max_length=32),
        ),
    ]
