# Generated by Django 4.1.5 on 2023-01-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0006_alter_uom_row_id_alter_uom_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='7a8ea2b7846043f09469f1e22b69fced', max_length=32),
        ),
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='bd3ded430cdf4bf49ce4d8c7dca42561', max_length=32),
        ),
    ]
