# Generated by Django 4.1.5 on 2023-01-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0007_alter_uom_row_id_alter_uom_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='dc86830c16a74df5b270820bd43ce4d2', max_length=32),
        ),
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='7be20797db604900b13903e5383517d1', max_length=32),
        ),
    ]
