# Generated by Django 4.1.8 on 2023-04-12 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static', models.BooleanField(default=False)),
                ('w', models.IntegerField()),
                ('moved', models.BooleanField(default=True)),
                ('h', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('l_type', models.CharField(max_length=10)),
                ('ROW_ID', models.CharField(default='*****', max_length=1000, null=True)),
                ('i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='widgets.widget')),
            ],
        ),
    ]
