# Generated by Django 4.1.4 on 2023-01-02 18:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uom_base_unit',
            fields=[
                ('A', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('B', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('C', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('D', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('RESULT', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('LAST_UPDT_USER', models.CharField(max_length=100, null=True)),
                ('LAST_UPDT_DATE', models.DateField(default='2023-01-02', null=True)),
                ('VERSION', models.CharField(default=uuid.uuid4, max_length=32)),
                ('DB_ID', models.CharField(max_length=32, null=True)),
                ('ROW_ID', models.CharField(db_index=True, default=uuid.uuid4, max_length=32, primary_key=True, serialize=False)),
                ('STATUS', models.CharField(max_length=10, null=True)),
                ('REV_GRP_ID', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
