# Generated by Django 4.1.5 on 2023-01-06 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uom_base_unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uom_base_unit',
            name='UOM_NAME',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='LAST_UPDT_DATE',
            field=models.DateField(default='2023-01-06', null=True),
        ),
    ]
