# Generated by Django 4.1.8 on 2023-04-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom_base_unit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uom_base_unit',
            name='QUALITY_TYPE',
        ),
        migrations.AddField(
            model_name='uom_base_unit',
            name='CULTURE',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uom_base_unit',
            name='QUANTITY_TYPE',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='LAST_UPDT_DATE',
            field=models.DateField(default='2023-04-12', null=True),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='d85d6b195aff4a42bcc5a3e6ead8f9f5', max_length=32),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='VERSION',
            field=models.CharField(default='c5b7f773620e43fabb14c7c5cb0c3dda', max_length=32),
        ),
    ]
