# Generated by Django 4.1.5 on 2023-01-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom_base_unit', '0003_alter_uom_base_unit_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom_base_unit',
            name='A',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='B',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='C',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='D',
            field=models.CharField(max_length=1000),
        ),
    ]
