# Generated by Django 4.1.5 on 2023-01-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom_base_unit', '0004_alter_uom_base_unit_a_alter_uom_base_unit_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom_base_unit',
            name='B',
            field=models.DecimalField(decimal_places=1000, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='VERSION',
            field=models.CharField(default='f1d1e0dd9ef343cb87fadc444f9aa38a', max_length=32),
        ),
    ]
