# Generated by Django 4.1.5 on 2023-01-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom_base_unit', '0005_alter_uom_base_unit_b_alter_uom_base_unit_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom_base_unit',
            name='B',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='VERSION',
            field=models.CharField(default='09d77dcefbf24bcb906a46e947c7f6a2', max_length=32),
        ),
    ]
