version: "3.8"

services:
  django:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
      args:
        VARIANT: 3.10-buster
    command: /start
    env_file:
      - .env7
    volumes:
      - .:/django
      # - static_volume:/django/staticfiles
      # - media_volume:/django/mediafiles
    depends_on:
      - redis
      - postgres
    ports:
      - "8000:8000"
    networks:
      - net
  postgres:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
    ports:
      - "5434:5432"
    networks:
      - net
  pgadmin:
    restart: always
    image: dpage/pgadmin4:latest
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASS}

networks:
  net:
    driver: bridge
volumes:
  postgres-data: null
  pgadmin-data: null
  mongodb-data: null
  redis-data: null
  # static_volume:
  # media_volume:
