# Generated by Django 4.0.8 on 2022-10-17 08:41

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='type',
            fields=[
                ('TYPE', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('TYPE_CLASS', models.CharField(max_length=50)),
                ('LABEL_ID', models.CharField(max_length=100, null=True)),
                ('CHANGE_INTERVAL', models.CharField(max_length=10, null=True)),
                ('LAYER_NAME', models.CharField(max_length=50)),
                ('DESCRIPTION_ID', models.CharField(max_length=100, null=True)),
                ('HIDDEN', models.CharField(max_length=5, null=True)),
                ('BASE_TYPE', models.CharField(max_length=14, null=True)),
                ('CODE_LIST_TYPE', models.CharField(max_length=50, null=True)),
                ('IS_QUICK_LINK', models.CharField(max_length=5, null=True)),
                ('PROP_TBL_NAME', models.CharField(max_length=50, null=True)),
                ('BASE_TBL_NAME', models.CharField(max_length=50, null=True)),
                ('TAG_TBL_NAME', models.CharField(max_length=50, null=True)),
                ('LAST_UPDT_USER', models.CharField(max_length=100, null=True)),
                ('LAST_UPDT_DATE', models.DateField(default=django.utils.timezone.now, null=True)),
                ('VERSION', models.CharField(default=uuid.uuid4, max_length=32)),
                ('DB_ID', models.CharField(max_length=32, null=True)),
                ('ROW_ID', models.CharField(db_index=True, default=uuid.uuid4, max_length=32)),
                ('STATUS', models.CharField(max_length=10, null=True)),
                ('REV_GRP_ID', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
