# Generated by Django 4.0.8 on 2022-11-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0012_alter_type_last_updt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='LAST_UPDT_DATE',
            field=models.DateField(default='2022-11-16', null=True),
        ),
    ]
