# Generated by Django 4.1.8 on 2023-04-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculated_tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculated_tags',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='799a0ceec9f34edcbf3e4db4d86cd3ad', max_length=32),
        ),
        migrations.AlterField(
            model_name='calculated_tags',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='a4cf53dce55941c6b605de04a8748d85', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='calculated_tags',
            name='TAG_ID',
            field=models.CharField(default='4dbbeb365b154551ac4c6c0a767c5ad9', max_length=32),
        ),
        migrations.AlterField(
            model_name='calculated_tags',
            name='VERSION',
            field=models.CharField(default='f9e773424ad64179965efc503e386384', max_length=32, null=True),
        ),
    ]
