# Generated by Django 4.1.8 on 2023-04-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculated_tag', '0002_alter_calculated_tags_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculated_tags',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='de2ce6c319f944cdbfb2586a89f0e696', max_length=32),
        ),
        migrations.AlterField(
            model_name='calculated_tags',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='e045de4fc4c147b5bdf72b9040b66399', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='calculated_tags',
            name='TAG_ID',
            field=models.CharField(default='7f03988aa6d54d0db13bd5d766dbf98c', max_length=32),
        ),
        migrations.AlterField(
            model_name='calculated_tags',
            name='VERSION',
            field=models.CharField(default='772575ed8eb24a4da247fcf8b95eba87', max_length=32, null=True),
        ),
    ]
