# Generated by Django 4.0.8 on 2022-11-01 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='page_resource_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CULTURE', models.CharField(max_length=10)),
                ('ID', models.CharField(max_length=100)),
                ('SHORT_LABEL', models.CharField(max_length=200, null=True)),
                ('PARENT', models.CharField(max_length=200, null=True)),
                ('ICON', models.CharField(max_length=100, null=True)),
                ('TITLE', models.CharField(max_length=50, null=True)),
                ('URL', models.CharField(max_length=500, null=True)),
                ('ROW_ID', models.CharField(db_index=True, default=uuid.uuid4, max_length=32)),
            ],
        ),
    ]
