# Generated by Django 4.0.8 on 2022-11-01 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page_resource_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_resource_list',
            name='MODEL',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
