# Generated by Django 3.2.9 on 2021-12-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
