# Generated by Django 4.1.5 on 2023-01-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uoms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='9fa4a883f175411ca2dd88d750dc2f72', max_length=32),
        ),
    ]
