# Generated by Django 4.1.5 on 2023-01-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uoms', '0002_alter_uom_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='981b333272754804bfa53a1cb05a6ef0', max_length=32),
        ),
    ]
