# Generated by Django 4.1.5 on 2023-01-10 00:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uoms', '0003_alter_uom_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='uom',
            name='LAYER_NAME',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='051131238bff43c6b2cd65d9664fd453', max_length=32),
        ),
    ]
