# Generated by Django 4.1.8 on 2023-04-19 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0003_alter_item_create_source_alter_item_end_datetime_and_more'),
        ('bi_widgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bi_dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=1000)),
                ('CULTURE', models.CharField(db_index=True, max_length=10)),
                ('LAYER_NAME', models.CharField(max_length=50)),
                ('ROW_ID', models.CharField(default='*****', max_length=32, null=True)),
                ('ITEM_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('WIDGETS', models.ManyToManyField(blank=True, related_name='widgets', to='bi_widgets.bi_widget')),
            ],
        ),
    ]
