# Generated by Django 4.1.8 on 2023-04-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roles_type',
            fields=[
                ('ROLES_TYPE', models.CharField(max_length=100)),
                ('ROLES_INFO', models.CharField(max_length=100)),
                ('ROW_ID', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
    ]
