# Generated by Django 4.0.8 on 2022-11-22 15:49

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ITEM_ID', models.CharField(db_index=True, default=uuid.uuid4, max_length=32)),
                ('EVENT_TYPE', models.CharField(max_length=14)),
                ('TAG_ID', models.CharField(default='2c4aee019b8a42d0b3cdf02743b043f7', max_length=32)),
                ('START_DATE_TIME', models.DateField(default=django.utils.timezone.now)),
                ('PARENT_TAG_ID', models.CharField(max_length=32, null=True)),
                ('NAME', models.CharField(max_length=100, null=True)),
                ('DESCRIPTION', models.CharField(max_length=1000, null=True)),
                ('UOM', models.CharField(max_length=100, null=True)),
                ('DATA_TYPE', models.CharField(max_length=100, null=True)),
                ('DERIVE_EQUATION', models.CharField(max_length=1000, null=True)),
                ('EXCEPTION_DEV', models.CharField(max_length=1000, null=True)),
                ('EXCEPTION_DEV_TYPE', models.CharField(max_length=1000, null=True)),
                ('NODE_NAME', models.CharField(max_length=100, null=True)),
                ('PROCESS_NAME', models.CharField(max_length=100, null=True)),
                ('SOURCE_NAME', models.CharField(max_length=100, null=True)),
                ('STEPPED', models.CharField(max_length=100, null=True)),
                ('DATA_ACCESS_TYPE', models.CharField(max_length=200, null=True)),
                ('NODE_DUMP', models.CharField(max_length=2000, null=True)),
                ('NORMAL_MAXIMUM', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('NORMAL_MINIMUM', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('LIMIT_LOLO', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('LIMIT_HIHI', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('EVENT_NOTIFIER', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('NODE_CLASS', models.CharField(max_length=20, null=True)),
                ('HISTORIZING', models.CharField(max_length=10, null=True)),
                ('MINIMUM_SAMPLING_INTERVAL', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('PERIOD', models.CharField(max_length=20, null=True)),
                ('END_DATE_TIME', models.DateField(default='9000-01-01')),
                ('LAST_UPDATE_USER', models.CharField(max_length=100, null=True)),
                ('LAST_UPDATE_DATE', models.DateField(default=django.utils.timezone.now)),
                ('VERSION', models.CharField(default=uuid.uuid4, max_length=32, null=True)),
                ('DB_ID', models.CharField(max_length=32, null=True)),
                ('ROW_ID', models.CharField(db_index=True, default=uuid.uuid4, max_length=32, null=True)),
                ('STATUS', models.CharField(max_length=10, null=True)),
                ('REV_GRP_ID', models.CharField(max_length=32, null=True)),
                ('UPDATE_SOURCE', models.CharField(default='x', max_length=1, null=True)),
                ('CREATE_SOURCE', models.CharField(default='x', max_length=1, null=True)),
            ],
        ),
    ]
