# Generated by Django 4.1.3 on 2022-11-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='8bec8807783d4d03ac8856e6febeccf0', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='e7558e9921c34e1c84225fa45d4bb515', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='41dab2206e164e9a9ee07e554745b206', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='VERSION',
            field=models.CharField(default='b97686eda32c45898484e655c2e13ac3', max_length=32, null=True),
        ),
    ]
