# Generated by Django 4.1.8 on 2023-04-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='c58cf3913fad4e82bc992ca9a6f196dd', max_length=32, primary_key=True, serialize=False),
        ),
    ]
