# Generated by Django 4.0.8 on 2022-11-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='0d9e764c1ebf4851a8e44383cd7af272', max_length=32),
        ),
    ]
