# Generated by Django 4.1.3 on 2022-11-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='c79e621e179e438c897e9515b41bc9e1', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='42d8103dc83c411d80d4e4acb6bd98b0', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='123edcbeca06474283b2a863f0c1af1b', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='VERSION',
            field=models.CharField(default='3bbed08a71c74ecab8bf4c0e7347ec32', max_length=32, null=True),
        ),
    ]
