# Generated by Django 4.1.8 on 2023-04-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_tags_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='780d9beebec14d789341fece115ee86c', max_length=32, primary_key=True, serialize=False),
        ),
    ]
