# Generated by Django 4.1.8 on 2023-04-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_alter_tags_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='2f58ba7e8d8e431280a48f498bb83c1b', max_length=32, primary_key=True, serialize=False),
        ),
    ]
