# Generated by Django 4.1.3 on 2022-12-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_alter_tags_create_source_alter_tags_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='7f14efc1b7834f3593c41d2909724b02', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='a91643a35bc5491ab0b68fd0abd3fb7f', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='8ddbf09ff06846c58e2dea8188c37fcc', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='VERSION',
            field=models.CharField(default='ce967d3484b7415fb1977809592229bb', max_length=32, null=True),
        ),
    ]
