# Generated by Django 4.1.3 on 2022-11-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_alter_tags_item_id_alter_tags_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='05f4405fb9294fcf8ab8278713a59dfa', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='698da7b204cb43649fce744fd543b796', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='ac91e067b0f145c2a987a7d26f5c6f98', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='VERSION',
            field=models.CharField(default='b80b162ffa824ea9b3b6a21698abefa7', max_length=32, null=True),
        ),
    ]
