# Generated by Django 4.1.3 on 2022-12-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_alter_tags_item_id_alter_tags_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='d278e44497144edbae4f9c4448efb976', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='c501bb3d0e9042019815fd3d22f5c949', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='2d9ac75c15844191bc34dcd7aecc997d', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='VERSION',
            field=models.CharField(default='fff8b9cc02774479bb1ca19c727b0a5d', max_length=32, null=True),
        ),
    ]
