# Generated by Django 4.1.3 on 2022-11-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0007_alter_tags_item_id_alter_tags_row_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='START_DATE_TIME',
            new_name='START_DATETIME',
        ),
        migrations.AlterField(
            model_name='tags',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='cca406e648944a21953b22ab27638126', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='cbcfb8d78f66494285a1fbbb8bda90d7', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='f7d2b31338704c9ba5f9fed143ef8f95', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='VERSION',
            field=models.CharField(default='ac8c99f3790c435085ad2e59f3d55b64', max_length=32, null=True),
        ),
    ]
