# Generated by Django 4.1.4 on 2022-12-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0008_alter_tags_item_id_alter_tags_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='dbc4c1c9b41e4072af24b0de064608e4', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='a93def9559ac4be998b509c3cbdfd343', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='15bf18b41b404f42b423c0b2b142b1c4', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='VERSION',
            field=models.CharField(default='9fe03c647fb846f29365159c367bcd86', max_length=32, null=True),
        ),
    ]
