# Generated by Django 4.1.3 on 2022-11-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0008_alter_tags_item_id_alter_tags_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='1a29a0de1d244ea0ac04d655eea276b7', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='838c8e55da3942419570c4ad3dcd8b40', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='52e5b1d2b63e42cdb801a4e461ee826b', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='VERSION',
            field=models.CharField(default='4ac723ee29d94256aaafd7fdf78a92e5', max_length=32, null=True),
        ),
    ]
