# Generated by Django 4.1.3 on 2022-11-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0009_alter_tags_item_id_alter_tags_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='033ec224f0904a1097bbc7685704a2be', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='846f059b3ad54446ac1a8856f4ca42dc', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='832b385e38c5446a962f65c29afc71e0', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='VERSION',
            field=models.CharField(default='2f7a7a0c7e6947e5bcdbc346cffdd621', max_length=32, null=True),
        ),
    ]
