# Generated by Django 4.1.3 on 2022-11-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0010_alter_tags_item_id_alter_tags_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='d320480af6e7446bba64e9a3bf93bf33', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='eb2e0a304353410c884007bd0ec38f2e', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='d290b90cbff84292be879cd9ce02491f', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='VERSION',
            field=models.CharField(default='c45d23cbce484166b53aa81509f9625e', max_length=32, null=True),
        ),
    ]
