# Generated by Django 4.1.3 on 2022-11-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0011_alter_tags_item_id_alter_tags_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='CREATE_SOURCE',
            field=models.CharField(default='x', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='3a87aa68d7164e31969b994b5338b31f', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='d636e8441e864c29a0fd686b0576fc96', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='447c449a1bfb43d78b05d7ba9aa4eda6', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='UPDATE_SOURCE',
            field=models.CharField(default='x', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='VERSION',
            field=models.CharField(default='c7f3c323b70542deb55f2f4173d564af', max_length=32, null=True),
        ),
    ]
