# Generated by Django 4.1.3 on 2022-11-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0012_alter_tags_create_source_alter_tags_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='f1a0f884b7dd4b06b41f5faf7a1e961c', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='53b173e9c52a456991d8905efc39818b', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='1c739198441448fa8fb32db9e3f213a0', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='VERSION',
            field=models.CharField(default='902634df5c194762a733a39a1ca88a04', max_length=32, null=True),
        ),
    ]
