# Generated by Django 4.1.3 on 2022-11-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0014_alter_tags_item_id_alter_tags_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='eebf7652fe8145c59ddb41681c65fbc0', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='6fb8ba78b09e414c95d555c32a30bd65', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='21b676fb99bf4965b5a8fba61d9e6011', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='VERSION',
            field=models.CharField(default='0aaac02d3ec4488dbc9898cfb32f2a0d', max_length=32, null=True),
        ),
    ]
