# Generated by Django 4.1.3 on 2022-11-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0015_alter_tags_item_id_alter_tags_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='3dd4976f513e43899bfb3fb6403b324a', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='6f23288304874e25ad0df30d18498b0e', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='7cf14c99f90a457f9c0515aa20852ca2', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='VERSION',
            field=models.CharField(default='fe12c19f5f5a49dbba1c8e5ac48740e2', max_length=32, null=True),
        ),
    ]
