# Generated by Django 4.1.3 on 2022-11-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0017_alter_tags_item_id_alter_tags_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='863c3d960b6c4c76a567f095814120f9', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='d0d5fb9d14674d639a4e4c90f161cce4', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='8c1220af63324a379c1ecd1318b0d9eb', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='VERSION',
            field=models.CharField(default='6a6eaab5dc6f4cb88e6a713daba82c03', max_length=32, null=True),
        ),
    ]
