# Generated by Django 4.1.3 on 2022-11-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0018_alter_tags_item_id_alter_tags_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='456ed8ece3e04f35b017d1675d5d9792', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='91f971138559461cb6964c6ed54fbda8', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='6fec7bd9b21a4e7584ccb25d78d497ea', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='VERSION',
            field=models.CharField(default='ab33fbd47d024b62bdb6312a431d6935', max_length=32, null=True),
        ),
    ]
