# Generated by Django 4.1.3 on 2022-11-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0019_alter_tags_item_id_alter_tags_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='00f4a416a7034a84b31038f925a1b60f', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='3fd66f60e82f4f90bf27dc3b6b3ab72f', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='66dc6c5387624afa99d615606902258e', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='VERSION',
            field=models.CharField(default='538b4c65b03d483b95ae2011a9da596b', max_length=32, null=True),
        ),
    ]
