# Generated by Django 4.1.3 on 2022-11-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0020_alter_tags_item_id_alter_tags_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='6d6881dc395c45509fa5805273c7db52', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='96de93f39582402ebd31839cf89586ac', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='933d88ad17eb4a08945807ff972d95c9', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags',
            name='VERSION',
            field=models.CharField(default='39209470875046cba08a6d0d6553cc05', max_length=32, null=True),
        ),
    ]
