# Generated by Django 3.2.8 on 2021-11-29 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='parent',
            new_name='company_ref',
        ),
    ]
