# Generated by Django 3.2.9 on 2021-12-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='product',
            field=models.CharField(blank=True, db_column='product', max_length=100, null=True, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='battery',
            name='type',
            field=models.CharField(blank=True, db_column='type', max_length=100, null=True, verbose_name='Type'),
        ),
    ]
