# Generated by Django 4.1.8 on 2023-04-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='roles_property',
            fields=[
                ('ROLES_TYPE', models.CharField(max_length=100)),
                ('CREATE', models.BooleanField(default=False)),
                ('READ', models.BooleanField(default=False)),
                ('UPDATE', models.BooleanField(default=False)),
                ('DELETE', models.BooleanField(default=False)),
                ('ROW_ID', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('ROLES_ID', models.ManyToManyField(related_name='roles', to='roles.roles')),
            ],
        ),
    ]
