# Generated by Django 4.1.8 on 2023-04-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles_property',
            old_name='ROLES_TYPE',
            new_name='ROLES_TYPES',
        ),
        migrations.AddField(
            model_name='roles_property',
            name='ROLES_INFO',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
