# Generated by Django 4.1.8 on 2023-04-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles_property', '0002_rename_roles_type_roles_property_roles_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles_property',
            name='ROLES_ID',
        ),
    ]
