# Generated by Django 4.0.7 on 2022-10-07 14:52

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='type_property',
            fields=[
                ('TYPE', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('PROPERTY_NAME', models.CharField(max_length=15)),
                ('PROP_GRP', models.CharField(max_length=50, null=True)),
                ('PROP_GRP_PRNT', models.CharField(max_length=50, null=True)),
                ('LABEL_ID', models.CharField(max_length=100, null=True)),
                ('TABLE_NAME', models.CharField(max_length=50, null=True)),
                ('COLUMN_NAME', models.CharField(max_length=50, null=True)),
                ('PROPERTY_TYPE', models.CharField(max_length=100, null=True)),
                ('PROPERTY_CLASS', models.CharField(max_length=100, null=True)),
                ('UNICODE', models.CharField(max_length=5, null=True)),
                ('CODE_LIST', models.CharField(max_length=100, null=True)),
                ('CODE_LIST_FLTR', models.CharField(max_length=100, null=True)),
                ('CODE_LIST_LVL', models.DecimalField(decimal_places=0, max_digits=18, null=True)),
                ('PARENT_CL_PROP', models.CharField(max_length=15, null=True)),
                ('VALUE_FILTER', models.CharField(max_length=100, null=True)),
                ('UI_EDIT_CLASS', models.CharField(max_length=100, null=True)),
                ('SORT_ORDER', models.DecimalField(decimal_places=0, max_digits=18, null=True)),
                ('MANDATORY', models.CharField(max_length=5, null=True)),
                ('HIDDEN', models.CharField(max_length=5, null=True)),
                ('IS_KEY', models.CharField(max_length=5, null=True)),
                ('LENGTH', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('DECIMALS', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('UOM', models.CharField(max_length=50, null=True)),
                ('CHANGE_INTERVAL', models.CharField(default='ChangeInterval', max_length=10, null=True)),
                ('DEFAULT_VALUE', models.CharField(max_length=50, null=True)),
                ('LAYER_NAME', models.CharField(max_length=50)),
                ('DESCRIPTION_ID', models.CharField(max_length=100, null=True)),
                ('LAST_UPDT_USER', models.CharField(max_length=100, null=True)),
                ('LAST_UPDT_DATE', models.DateField(default=django.utils.timezone.now, null=True)),
                ('VERSION', models.CharField(default=uuid.uuid4, max_length=32)),
                ('DB_ID', models.CharField(max_length=32, null=True)),
                ('ROW_ID', models.CharField(db_index=True, default=uuid.uuid4, max_length=32)),
                ('STATUS', models.CharField(max_length=10, null=True)),
                ('REV_GRP_ID', models.CharField(max_length=32, null=True)),
                ('PROP_UNIQUE', models.CharField(max_length=20, null=True)),
                ('ALLOW_MULTI_EDIT', models.CharField(max_length=5, null=True)),
                ('DEF_ACCUM_FUNC', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
