# Generated by Django 4.0.8 on 2022-10-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_property',
            name='CHANGE_INTERVAL',
            field=models.CharField(default='CH', max_length=10, null=True),
        ),
    ]
