# Generated by Django 4.1.3 on 2022-11-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_property', '0002_alter_type_property_change_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_property',
            name='PROPERTY_NAME',
            field=models.CharField(max_length=50),
        ),
    ]
