# Generated by Django 3.2.8 on 2021-11-08 21:
################################
from .admin_battery import *
from .admin_company import *
from .admin_completion import *
from .admin_field import *

# from .admin_pump import *
