#!/bin/bash

set -o errexit

set -o pipefail

set -o nounset

cd backend


# until python manage.py migrate
python3 manage.py migrate --no-input
python3 manage.py collectstatic --no-input
python manage.py runserver 0.0.0.0:8000

