# Generated by Django 4.0.8 on 2022-11-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_link',
            name='CREATE_SOURCE',
            field=models.CharField(default='x', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='item_link',
            name='UPDATE_SOURCE',
            field=models.CharField(default='x', max_length=1, null=True),
        ),
    ]
