# Generated by Django 3.2.8 on 2021-11-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='iefppuser',
            table='oauth',
        ),
    ]
