version: '3'
services: 
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/jovyan/
    ports:
    - "10000:8888"
  db:
    image: postgres
    restart: always
    volumes:
     - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1111
    ports:
    - "5432:5432"
volumes:
  pgdata: