version: '3'
services: 
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/jovyan/
    ports:
    - "10000:8888"

  db:
    container_name: pg_container
    image: postgres
    restart: always
    volumes:
     - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: system
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: test_db 
    ports:
    - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    restart: always 
    image: dpage/pgadmin4
    #volumes:
     # - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: manager
    ports:
      - "5050:80"
    #networks:
      #- net
volumes:
  pgdata: