# Generated by Django 4.0.6 on 2022-07-25 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code_list',
            old_name='CODE_TEXT',
            new_name='CODETEXT',
        ),
        migrations.RenameField(
            model_name='code_list',
            old_name='LEGACY_CODE',
            new_name='LEGACYCODE',
        ),
        migrations.RenameField(
            model_name='code_list',
            old_name='LIST_TYPE',
            new_name='LISTTYPE',
        ),
    ]
