# Generated by Django 4.0.5 on 2022-07-20 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='code_list',
        ),
        migrations.DeleteModel(
            name='item_property',
        ),
    ]
