# Generated by Django 4.0.6 on 2022-07-25 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_rename_code_text_code_list_codetext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_list',
            name='LAST_UPDT_DATE',
            field=models.DateField(default=datetime.date(2022, 7, 25), null=True),
        ),
    ]
